const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");

const read = (path) => readFileSync(path, "utf8");
const audio = read("client/src/hooks/useClubAudio.ts");
const home = read("client/src/pages/Home.tsx");
const top = read("client/src/components/ClubFloor3D.tsx");
const pov = read("client/src/components/PovPreview.tsx");
const side = read("client/src/components/SideScene.tsx");
const app = read("client/src/App.tsx");
const miniature = read("client/src/components/SpeakerMiniature.tsx");
const mixer = read("client/src/components/SpeakerMixer.tsx");

assert.match(audio, /syncTopology/);
assert.match(audio, /syncSpeakerDsp/);
assert.match(audio, /syncSpeakerPositions/);
assert.match(audio, /syncListenerPosition/);
assert.match(audio, /syncListenerOrientation/);
assert.match(audio, /cache: SpeakerCache/);
assert.doesNotMatch(audio, /setActivityBySpeaker/);
assert.doesNotMatch(audio, /speakers\.find\(/);
assert.match(audio, /isPlaying \|\| hasResidual/);
assert.match(home, /useSpeakerActivity\(activityStore\)/);
assert.doesNotMatch(home, /activityBySpeaker, togglePlayback/);
assert.match(top, /frameloop="demand"/);
assert.match(top, /requestAnimationFrame\(applyPending\)/);
assert.match(pov, /frameloop="demand"/);
assert.match(pov, /requestAnimationFrame\(flushLook\)/);
assert.match(side, /getBoundingClientRect\(\)/);
assert.match(side, /requestAnimationFrame\(flush\)/);
assert.match(app, /lazy\(\(\) => import\("\.\/components\/SpeakerModelValidation"\)\)/);
assert.match(miniature, /const cabinet = makeChamferCabinet/);
assert.match(miniature, /useMemo\(createSpeakerMaterials, \[\]\)/);
assert.match(miniature, /speakerBandProfile/);
assert.match(miniature, /typeGlowGain/);
assert.match(miniature, /setFrequencyColor/);
assert.match(miniature, /materials\.horn\.emissiveIntensity/);
assert.match(miniature, /materials\.driver\.emissiveIntensity/);
assert.match(miniature, /invalidate\(\)/);
assert.doesNotMatch(miniature, /new THREE\.(PointLight|SpotLight)/);
assert.doesNotMatch(miniature, /EffectComposer|UnrealBloomPass/);
assert.doesNotMatch(miniature, /DataTexture|SpriteMaterial|LocalGlow/);
assert.doesNotMatch(miniature, /visible=\{activity/);
assert.doesNotMatch(miniature, /opacity=\{activity/);
assert.match(home, /<SpeakerMixer/);
assert.match(home, /onLevelsChange=\{updateSpeakerLevels\}/);
assert.match(mixer, /useSpeakerActivity\(store\)/);
assert.match(mixer, /requestAnimationFrame\(applyLatest\)/);
assert.match(mixer, /setPointerCapture/);
assert.doesNotMatch(mixer, /createAnalyser|createGain|createPanner/);
assert.doesNotMatch(mixer, /DrawerContent|DrawerPrimitive/);
assert.match(audio, /const SWEEP_START_HZ = 20/);
assert.match(audio, /const SWEEP_END_HZ = 20_000/);
assert.match(audio, /const SWEEP_DURATION_SECONDS = 15/);
assert.match(audio, /oscillator\.frequency\.exponentialRampToValueAtTime\(SWEEP_END_HZ, now \+ SWEEP_DURATION_SECONDS\)/);
assert.match(audio, /oscillator\.stop\(now \+ SWEEP_DURATION_SECONDS\)/);
assert.match(audio, /desiredSource && shouldPlay && !voices\.has\(desiredSource\.id\)/);
assert.match(home, /id: "sweep", name: "20 Hz → 20 kHz · 15 sec"/);

console.log("performance architecture tests passed");
