const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const home = readFileSync("client/src/pages/Home.tsx", "utf8");
const floor = readFileSync("client/src/components/ClubFloor3D.tsx", "utf8");
const recipes = readFileSync("client/src/lib/systemRecipes.ts", "utf8");
assert.match(recipes, /SYSTEM_PRESETS\.map\(recipeFromPreset\)/, "legacy recipes remain internally supported");
assert.match(home, /releaseRecipes\.map/, "the browser exposes only release-compatible recipes");
assert.match(home, /recipe\.ingredients\.every\(\(item\) => releaseSpeakerModelIds\.includes\(item\.modelId\)\)/);
assert.match(home, /FREE BUILD/);
assert.match(home, /setCurrentRecipeId\(recipe\.id\); setRecipeDetailId\(recipe\.id\)/);
assert.doesNotMatch(home, /prepareRecipeMaterials|getMissingRecipeIngredients|createMaterialStagingPlan|resolvePhysicalCollisions/);
assert.doesNotMatch(floor, /materialStaging|recipe-material-label/);
assert.match(home, /onAdd\(modelId\)/);
assert.match(home, /getRecipeProgress\(recipeDetail, speakers\)/);
assert.match(home, /recipeProgress\.ingredients\.reduce/);
console.log("release recipe UX static tests passed");
