/**
 * Spatial Installation UI: controls are deliberately quiet so the monochrome speaker arrangement remains the visual identity.
 * Existing audio, grid snapping, 3D height, listener movement, source choice, type, level, mute and removal behavior are unchanged.
 */
import { useRef, useState } from "react";
import { ChevronDown, Headphones, Music2, Pause, Play, Plus, RotateCcw, Volume2, VolumeX, X } from "lucide-react";
import { initialHeightForKind, type ClubListener, type ClubSource, type ClubSpeaker, type SpeakerKind, useClubAudio } from "@/hooks/useClubAudio";
import ClubFloor3D from "@/components/ClubFloor3D";
import "../club-floor-3d.css";
import "../floor-instrument.css";
import "../spatial-installation.css";

const logoMark = "/manus-storage/clubcraft-mark_066a01b1.png";
const speakerMeta: Record<SpeakerKind, { label: string; color: string }> = { sub: { label: "Sub", color: "#2b2d2b" }, woofer: { label: "Woofer", color: "#73746e" }, full: { label: "Full Range", color: "#eeeeea" }, mid: { label: "Mid", color: "#aaa9a2" }, high: { label: "High", color: "#c9c8c1" } };
const makeSpeaker = (id: string, kind: SpeakerKind, x: number, y: number, level: number): ClubSpeaker => ({ id, kind, label: speakerMeta[kind].label, position: { x, y, z: initialHeightForKind[kind] }, level, muted: false, responseProfileId: kind, activity: 0 });
const initialSpeakers: ClubSpeaker[] = [makeSpeaker("sub-1", "sub", .1667, .75, .78), makeSpeaker("full-1", "full", .3333, .3333, .72), makeSpeaker("full-2", "full", .6667, .3333, .72), makeSpeaker("high-1", "high", .8333, .6667, .6)];
const initialListener: ClubListener = { position: { x: .5, y: .72, z: .5 }, orientation: { forwardX: 0, forwardY: 0, forwardZ: -1 } };
const clubTracks: ClubSource[] = [{ id: "pulse", name: "Deep Pulse", category: "official", color: "#e65b4a" }, { id: "rain", name: "Rain Room", category: "official", color: "#d6aa43" }, { id: "bronze", name: "Bronze Air", category: "official", color: "#4bbd92" }];
const gridSpawnPoints = [{ x: .5, y: .5 }, { x: .4167, y: .5 }, { x: .5833, y: .5 }, { x: .5, y: .5833 }, { x: .5, y: .4167 }];
const clamp = (value: number) => Math.max(.07, Math.min(.93, value));
const snapToGrid = (value: number) => clamp(Math.round(value * 12) / 12);

export default function Home() {
  const [speakers, setSpeakers] = useState<ClubSpeaker[]>(initialSpeakers); const [listener, setListener] = useState<ClubListener>(initialListener); const [sources, setSources] = useState<ClubSource[]>(clubTracks); const [selectedSourceId, setSelectedSourceId] = useState("pulse"); const [selectedSpeakerId, setSelectedSpeakerId] = useState("full-1"); const [newSpeakerKind, setNewSpeakerKind] = useState<SpeakerKind>("full"); const [showSourcePicker, setShowSourcePicker] = useState(false); const fileInputRef = useRef<HTMLInputElement>(null);
  const { isPlaying, togglePlayback } = useClubAudio(speakers, listener, sources, selectedSourceId);
  const selectedSource = sources.find((source) => source.id === selectedSourceId) ?? sources[0]; const selectedSpeaker = speakers.find((speaker) => speaker.id === selectedSpeakerId) ?? speakers[0];
  const moveSpeakerToGrid = (id: string, position: { x: number; y: number }) => setSpeakers((now) => now.map((speaker) => speaker.id === id ? { ...speaker, position: { ...speaker.position, x: snapToGrid(position.x), y: snapToGrid(position.y) } } : speaker));
  const addSpeaker = () => { if (speakers.length >= 16) return; const id = `${newSpeakerKind}-${Date.now()}`; setSpeakers((now) => { const point = gridSpawnPoints[now.length % gridSpawnPoints.length]; return [...now, makeSpeaker(id, newSpeakerKind, point.x, point.y, .68)]; }); setSelectedSpeakerId(id); };
  const addLocalSound = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const id = `local-${Date.now()}`; setSources((now) => [...now, { id, name: file.name.replace(/\.[^/.]+$/, ""), category: "local", color: "#797a73", localUrl: URL.createObjectURL(file) }]); setSelectedSourceId(id); setShowSourcePicker(false); event.target.value = ""; };
  const updateSpeaker = (update: Partial<ClubSpeaker>) => { if (!selectedSpeaker) return; setSpeakers((now) => now.map((speaker) => speaker.id === selectedSpeaker.id ? { ...speaker, ...update, label: update.kind ? speakerMeta[update.kind].label : speaker.label, responseProfileId: update.kind ?? speaker.responseProfileId } : speaker)); };
  const removeSelected = () => { if (!selectedSpeaker || speakers.length <= 1) return; setSpeakers((now) => now.filter((speaker) => speaker.id !== selectedSpeaker.id)); setSelectedSpeakerId(speakers.find((speaker) => speaker.id !== selectedSpeaker.id)?.id ?? ""); };
  const chooseSource = (id: string) => { setSelectedSourceId(id); setShowSourcePicker(false); };

  return <main className="instrument-app spatial-installation"><header className="instrument-header"><div className="spatial-brand"><img src={logoMark} alt="Club Craft" /><span className="spatial-word"><b>Club</b><em>Craft</em></span><small>spatial sound</small></div><div className="source-trigger-wrap"><button className="source-trigger" onClick={() => setShowSourcePicker((open) => !open)} aria-haspopup="dialog" aria-expanded={showSourcePicker}><i style={{ backgroundColor: selectedSource?.color }} /><span>{selectedSource?.name ?? "Choose sound"}</span><ChevronDown size={14} /></button>{showSourcePicker && <section className="source-popover" role="dialog" aria-label="Choose sound"><p className="source-popover-label">Club Craft picks</p>{sources.map((source) => <button key={source.id} className={`source-choice ${source.id === selectedSourceId ? "active" : ""}`} onClick={() => chooseSource(source.id)}><i style={{ backgroundColor: source.color }} /><span><strong>{source.name}</strong><small>{source.category === "local" ? "Your file" : "Club Craft pick"}</small></span><Music2 size={13} /></button>)}<button className="source-upload" onClick={() => fileInputRef.current?.click()}><Plus size={14} /> Upload audio</button><p className="source-private"><Headphones size={12} /> Your file stays on this device.</p></section>}<input ref={fileInputRef} className="hidden-input" type="file" accept="audio/*" onChange={addLocalSound} /></div><div className="instrument-actions"><span className="headphone-note"><Headphones size={13} /> Best with headphones</span><button className={`instrument-play ${isPlaying ? "is-playing" : ""}`} onClick={() => void togglePlayback()}>{isPlaying ? <Pause size={14} fill="currentColor" /> : <Play size={14} fill="currentColor" />}{isPlaying ? "Pause" : "Play"}</button></div></header>
    <section className="instrument-stage"><ClubFloor3D speakers={speakers} listener={listener} selectedSpeakerId={selectedSpeakerId} signalActive={isPlaying} onSpeakerSelect={setSelectedSpeakerId} onSpeakerMove={moveSpeakerToGrid} onListenerMove={(position) => setListener((current) => ({ ...current, position: { ...current.position, ...position } }))} />
      <div className="speaker-composer"><select value={newSpeakerKind} onChange={(event) => setNewSpeakerKind(event.target.value as SpeakerKind)} aria-label="Speaker type">{(Object.keys(speakerMeta) as SpeakerKind[]).map((kind) => <option key={kind} value={kind}>{speakerMeta[kind].label}</option>)}</select><button onClick={addSpeaker}><Plus size={14} /> Add speaker</button></div>
      {selectedSpeaker && <aside className="spatial-inspector" aria-label="Selected speaker"><h2>{speakerMeta[selectedSpeaker.kind].label}</h2><label className="spatial-control"><span>Type</span><select value={selectedSpeaker.kind} onChange={(event) => updateSpeaker({ kind: event.target.value as SpeakerKind })}>{(Object.keys(speakerMeta) as SpeakerKind[]).map((kind) => <option key={kind} value={kind}>{speakerMeta[kind].label}</option>)}</select></label><label className="spatial-control"><span>Level</span><input type="range" min=".08" max="1" step=".01" value={selectedSpeaker.level} onChange={(event) => updateSpeaker({ level: Number(event.target.value) })} /></label><label className="spatial-control height-control"><span>Height</span><input type="range" min="0" max="1" step=".01" value={selectedSpeaker.position.z} onChange={(event) => updateSpeaker({ position: { ...selectedSpeaker.position, z: Number(event.target.value) } })} /><div className="height-stops" aria-hidden="true"><span>Floor</span><span>Ear</span><span>High</span></div></label><div className="inspector-actions"><button className={selectedSpeaker.muted ? "muted" : ""} onClick={() => updateSpeaker({ muted: !selectedSpeaker.muted })}>{selectedSpeaker.muted ? <VolumeX size={14} /> : <Volume2 size={14} />}{selectedSpeaker.muted ? "Unmute" : "Mute"}</button><button className="remove" onClick={removeSelected} disabled={speakers.length <= 1}>Remove</button></div></aside>}</section>
    <footer className="instrument-footer"><button onClick={() => { setSpeakers(initialSpeakers); setListener(initialListener); }}><RotateCcw size={13} /> Reset</button></footer></main>;
}
