/**
 * One ClubScene, three quiet projections. TOP edits X/Y; SIDE edits Y/Z; POV previews from the Listener without creating a second scene.
 * Existing sources, local audio, Speaker filters, level, height and HRTF infrastructure remain authoritative and unchanged.
 */
import { useRef, useState } from "react";
import { ChevronDown, Headphones, Music2, Pause, Play, Plus, RotateCcw, Volume2, VolumeX, X } from "lucide-react";
import { initialHeightForKind, type ClubListener, type ClubSource, type ClubSpeaker, type SpeakerKind, useClubAudio } from "@/hooks/useClubAudio";
import ClubFloor3D from "@/components/ClubFloor3D";
import SideScene from "@/components/SideScene";
import PovPreview from "@/components/PovPreview";
import "../club-floor-3d.css";
import "../floor-instrument.css";
import "../spatial-installation.css";
import "../three-views.css";
import "../dark-club.css";

type SceneView = "top" | "side" | "pov";
const logoMark = "/manus-storage/clubcraft-mark_066a01b1.png";
const speakerMeta: Record<SpeakerKind, { label: string; color: string }> = { sub: { label: "Sub", color: "#2b2d2b" }, woofer: { label: "Woofer", color: "#73746e" }, full: { label: "Full Range", color: "#eeeeea" }, mid: { label: "Mid", color: "#aaa9a2" }, high: { label: "High", color: "#c9c8c1" } };
const makeSpeaker = (id: string, kind: SpeakerKind, x: number, y: number, level: number): ClubSpeaker => ({ id, kind, label: speakerMeta[kind].label, position: { x, y, z: initialHeightForKind[kind] }, level, muted: false, responseProfileId: kind, activity: 0 });
const initialSpeakers: ClubSpeaker[] = [makeSpeaker("sub-1", "sub", .1667, .75, .78), makeSpeaker("full-1", "full", .3333, .3333, .72), makeSpeaker("full-2", "full", .6667, .3333, .72), makeSpeaker("high-1", "high", .8333, .6667, .6)];
const initialListener: ClubListener = { position: { x: .5, y: .72, z: .5 }, orientation: { yaw: 0, pitch: 0 } };
const clubTracks: ClubSource[] = [{ id: "pulse", name: "Deep Pulse", category: "official", color: "#e65b4a" }, { id: "rain", name: "Rain Room", category: "official", color: "#d6aa43" }, { id: "bronze", name: "Bronze Air", category: "official", color: "#4bbd92" }];
const gridSpawnPoints = [{ x: .5, y: .5 }, { x: .4167, y: .5 }, { x: .5833, y: .5 }, { x: .5, y: .5833 }, { x: .5, y: .4167 }];
const clamp = (value: number) => Math.max(.07, Math.min(.93, value));
const clampPitch = (value: number) => Math.max(-1.12, Math.min(1.12, value));
const initialViewFromUrl = (): SceneView => { const requested = new URLSearchParams(window.location.search).get("view"); return requested === "side" || requested === "pov" ? requested : "top"; };

export default function Home() {
  const [speakers, setSpeakers] = useState<ClubSpeaker[]>(initialSpeakers); const [listener, setListener] = useState<ClubListener>(initialListener); const [sources, setSources] = useState<ClubSource[]>(clubTracks); const [selectedSourceId, setSelectedSourceId] = useState("pulse"); const [selectedSpeakerId, setSelectedSpeakerId] = useState("full-1"); const [view, setView] = useState<SceneView>(initialViewFromUrl); const [showSourcePicker, setShowSourcePicker] = useState(false); const fileInputRef = useRef<HTMLInputElement>(null);
  const { isPlaying, activityBySpeaker, togglePlayback, playbackError, clearPlaybackError } = useClubAudio(speakers, listener, sources, selectedSourceId);
  const selectedSource = sources.find((source) => source.id === selectedSourceId) ?? sources[0]; const selectedSpeaker = speakers.find((speaker) => speaker.id === selectedSpeakerId) ?? speakers[0];
  const moveSpeakerTop = (id: string, position: { x: number; y: number }) => setSpeakers((now) => now.map((speaker) => speaker.id === id ? { ...speaker, position: { ...speaker.position, x: clamp(position.x), y: clamp(position.y) } } : speaker));
  const moveSpeakerSide = (id: string, position: { y: number; z: number }) => setSpeakers((now) => now.map((speaker) => speaker.id === id ? { ...speaker, position: { ...speaker.position, y: clamp(position.y), z: clamp(position.z) } } : speaker));
  const addSpeaker = (kind: SpeakerKind) => { if (speakers.length >= 16) return; const id = `${kind}-${Date.now()}`; setSpeakers((now) => { const point = gridSpawnPoints[now.length % gridSpawnPoints.length]; return [...now, makeSpeaker(id, kind, point.x, point.y, .68)]; }); setSelectedSpeakerId(id); };
  const addLocalSound = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const id = `local-${Date.now()}`; clearPlaybackError(); setSources((now) => [...now, { id, name: file.name.replace(/\.[^/.]+$/, ""), category: "local", color: "#797a73", localUrl: URL.createObjectURL(file) }]); setSelectedSourceId(id); setShowSourcePicker(false); event.target.value = ""; };
  const updateSpeaker = (update: Partial<ClubSpeaker>) => { if (!selectedSpeaker) return; setSpeakers((now) => now.map((speaker) => speaker.id === selectedSpeaker.id ? { ...speaker, ...update, label: update.kind ? speakerMeta[update.kind].label : speaker.label, responseProfileId: update.kind ?? speaker.responseProfileId } : speaker)); };
  const removeSpeaker = (id: string) => { if (speakers.length <= 1) return; setSpeakers((now) => now.filter((speaker) => speaker.id !== id)); setSelectedSpeakerId(speakers.find((speaker) => speaker.id !== id)?.id ?? ""); };
  const chooseSource = (id: string) => { setSelectedSourceId(id); setShowSourcePicker(false); };
  const turnListener = (yaw: number, pitch: number) => setListener((current) => ({ ...current, orientation: { yaw: current.orientation.yaw + yaw, pitch: clampPitch(current.orientation.pitch + pitch) } }));

  const visualSpeakers = speakers.map((speaker) => ({ ...speaker, activity: activityBySpeaker[speaker.id] ?? 0 }));
  return <main className={`instrument-app spatial-installation dark-club scene-view-${view}`}><header className="instrument-header"><div className="spatial-brand"><img src={logoMark} alt="Club Craft" /><span className="spatial-word"><b>Club</b><em>Craft</em></span><small>spatial sound</small></div><div className="source-trigger-wrap"><button className="source-trigger" onClick={() => setShowSourcePicker((open) => !open)} aria-haspopup="dialog" aria-expanded={showSourcePicker}><i style={{ backgroundColor: selectedSource?.color }} /><span>{selectedSource?.name ?? "Choose sound"}</span><ChevronDown size={14} /></button>{showSourcePicker && <section className="source-popover" role="dialog" aria-label="Choose sound"><p className="source-popover-label">Club Craft picks</p>{sources.map((source) => <button key={source.id} className={`source-choice ${source.id === selectedSourceId ? "active" : ""}`} onClick={() => chooseSource(source.id)}><i style={{ backgroundColor: source.color }} /><span><strong>{source.name}</strong><small>{source.category === "local" ? "Your file" : "Club Craft pick"}</small></span><Music2 size={13} /></button>)}<button className="source-upload" onClick={() => fileInputRef.current?.click()}><Plus size={14} /> Upload audio</button><p className="source-private"><Headphones size={12} /> Your file stays on this device.</p></section>}<input ref={fileInputRef} className="hidden-input" type="file" accept="audio/*" onChange={addLocalSound} /></div><div className="instrument-actions"><span className="headphone-note"><Headphones size={13} /> Best with headphones</span><button className={`instrument-play ${isPlaying ? "is-playing" : ""}`} onClick={() => void togglePlayback()}>{isPlaying ? <Pause size={14} fill="currentColor" /> : <Play size={14} fill="currentColor" />}{isPlaying ? "Pause" : "Play"}</button></div></header>
    <section className="instrument-stage"><div className="view-switcher" aria-label="Scene view">{(["top", "side", "pov"] as SceneView[]).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}>{item}</button>)}</div>{playbackError && <button className="local-audio-error" onClick={clearPlaybackError} role="status">{playbackError}<X size={13} /></button>}
      <div className="scene-surface" key={view}>{view === "top" && <ClubFloor3D speakers={visualSpeakers} listener={listener} selectedSpeakerId={selectedSpeakerId} signalActive={isPlaying} canRemove={speakers.length > 1} onSpeakerSelect={setSelectedSpeakerId} onSpeakerRemove={removeSpeaker} onSpeakerMove={moveSpeakerTop} onListenerMove={(position) => setListener((current) => ({ ...current, position: { ...current.position, ...position } }))} />}{view === "side" && <SideScene speakers={visualSpeakers} listener={listener} selectedSpeakerId={selectedSpeakerId} canRemove={speakers.length > 1} onSpeakerSelect={setSelectedSpeakerId} onSpeakerRemove={removeSpeaker} onSpeakerMove={moveSpeakerSide} />}{view === "pov" && <PovPreview speakers={visualSpeakers} listener={listener} onLook={turnListener} />}</div>
      {view !== "pov" && <><div className="speaker-composer speaker-icon-composer" aria-label="Add a speaker">{(Object.keys(speakerMeta) as SpeakerKind[]).map((kind) => <button key={kind} className={`speaker-type-icon ${kind}`} onClick={() => addSpeaker(kind)} aria-label={`Add ${speakerMeta[kind].label}`} title={`Add ${speakerMeta[kind].label}`}><i /><span>{speakerMeta[kind].label}</span></button>)}</div>{selectedSpeaker && <aside className="spatial-inspector" aria-label="Selected speaker"><h2>{speakerMeta[selectedSpeaker.kind].label}</h2><label className="spatial-control"><span>Type</span><select value={selectedSpeaker.kind} onChange={(event) => updateSpeaker({ kind: event.target.value as SpeakerKind })}>{(Object.keys(speakerMeta) as SpeakerKind[]).map((kind) => <option key={kind} value={kind}>{speakerMeta[kind].label}</option>)}</select></label><label className="spatial-control"><span>Level</span><input type="range" min=".08" max="1" step=".01" value={selectedSpeaker.level} onChange={(event) => updateSpeaker({ level: Number(event.target.value) })} /></label><label className="spatial-control height-control"><span>Height</span><input type="range" min="0" max="1" step=".01" value={selectedSpeaker.position.z} onChange={(event) => updateSpeaker({ position: { ...selectedSpeaker.position, z: Number(event.target.value) } })} /><div className="height-stops" aria-hidden="true"><span>Floor</span><span>Ear</span><span>High</span></div></label><div className="inspector-actions"><button className={selectedSpeaker.muted ? "muted" : ""} onClick={() => updateSpeaker({ muted: !selectedSpeaker.muted })}>{selectedSpeaker.muted ? <VolumeX size={14} /> : <Volume2 size={14} />}{selectedSpeaker.muted ? "Unmute" : "Mute"}</button></div></aside>}</>}
      </section><footer className="instrument-footer"><button onClick={() => { setSpeakers(initialSpeakers); setListener(initialListener); }}><RotateCcw size={13} /> Reset</button></footer></main>;
}
