/* Club Craft Reggae rule: warm painted plywood cabinets reveal frequency color only from horn throats and tweeter emitters, never from the cabinet shell. */
import * as THREE from "three";
import { useEffect, useMemo } from "react";
import { useThree } from "@react-three/fiber";
import type { SpeakerKind } from "@/hooks/useClubAudio";
import { getSpeakerModel, type SpeakerModelId } from "@/lib/speakerModels";

type Props = { modelId: SpeakerModelId; kind: SpeakerKind; activity: number; selected?: boolean };
const box = new THREE.BoxGeometry(1, 1, 1); const tweeter = new THREE.CylinderGeometry(1, 1, .035, 18); tweeter.rotateX(Math.PI / 2); const selection = new THREE.MeshBasicMaterial({ color: "#d5c2a8", transparent: true, opacity: .035, side: THREE.BackSide });
const LOW = new THREE.Color("#ff3b30"); const KICK = new THREE.Color("#ff9f0a"); const MID = new THREE.Color("#ffd60a"); const HIGH = new THREE.Color("#32d05b");
function hornGeometry(mouthWidth: number, mouthHeight: number, throatWidth: number, throatHeight: number, depth: number) { const positions = new Float32Array([-mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, mouthHeight / 2, 0, -mouthWidth / 2, mouthHeight / 2, 0, -throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, throatHeight / 2, -depth, -throatWidth / 2, throatHeight / 2, -depth]); const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3)); geometry.setIndex([0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7]); geometry.computeVertexNormals(); return geometry; }
const scoopHorn = hornGeometry(1.16, .72, .22, .16, .66); const scoopGlow = hornGeometry(.74, .43, .12, .08, .52); const kickHorn = hornGeometry(1.08, .44, .25, .12, .45); const kickGlow = hornGeometry(.67, .25, .14, .07, .34); const midHorn = hornGeometry(.94, .46, .14, .09, .42); const midGlow = hornGeometry(.58, .27, .08, .05, .31);
function useReggaeMaterials(kind: SpeakerKind, activity: number) { const { invalidate } = useThree(); const materials = useMemo(() => ({ cabinet: new THREE.MeshStandardMaterial({ color: "#494036", roughness: .89, metalness: 0 }), edge: new THREE.MeshStandardMaterial({ color: "#786850", roughness: .75, metalness: .02 }), horn: new THREE.MeshStandardMaterial({ color: "#130f0b", roughness: .86, side: THREE.DoubleSide }), emitter: new THREE.MeshStandardMaterial({ color: "#000000", emissive: "#000000", emissiveIntensity: 0, roughness: .65, side: THREE.DoubleSide, toneMapped: false }), throat: new THREE.MeshStandardMaterial({ color: "#080604", roughness: .92 }) }), []); useEffect(() => () => Object.values(materials).forEach((material) => material.dispose()), [materials]); useEffect(() => { const active = Math.pow(THREE.MathUtils.clamp(activity, 0, 1), .92); const color = kind === "sub" ? LOW : kind === "woofer" ? KICK : kind === "mid" ? MID : HIGH; materials.emitter.color.copy(color).multiplyScalar(active > 0 ? .1 + active * .9 : 0); materials.emitter.emissive.copy(color); materials.emitter.emissiveIntensity = active * (kind === "high" ? 1.1 : .96); invalidate(); }, [activity, invalidate, kind, materials]); return materials; }
function Horn({ geometry, emitterGeometry, y, frontZ, materials }: { geometry: THREE.BufferGeometry; emitterGeometry: THREE.BufferGeometry; y: number; frontZ: number; materials: ReturnType<typeof useReggaeMaterials> }) { return <group position={[0, y, frontZ]}><mesh geometry={geometry} material={materials.horn} /><mesh geometry={emitterGeometry} position={[0, 0, .004]} material={materials.emitter} /></group>; }
function Scoop({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-scoop", "sub").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><mesh geometry={box} position={[0, .57, front + .015]} scale={[body.width * .86, .22, .04]} material={materials.edge} /><Horn geometry={scoopHorn} emitterGeometry={scoopGlow} y={-.32} frontZ={front} materials={materials} /><mesh geometry={box} position={[-.3, -.18, front - .28]} rotation={[0, .33, 0]} scale={[.1, .46, .04]} material={materials.horn} /><mesh geometry={box} position={[.3, -.18, front - .32]} rotation={[0, -.33, 0]} scale={[.1, .46, .04]} material={materials.horn} /><mesh geometry={box} position={[0, -.32, front - .61]} scale={[.18, .13, .035]} material={materials.throat} /></>; }
function Kick({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-kick", "woofer").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><Horn geometry={kickHorn} emitterGeometry={kickGlow} y={-.02} frontZ={front} materials={materials} /><mesh geometry={box} position={[0, .31, front + .015]} scale={[body.width * .82, .055, .038]} material={materials.edge} /><mesh geometry={box} position={[0, -.31, front + .015]} scale={[body.width * .82, .055, .038]} material={materials.edge} /></>; }
function MidHorn({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-mid-horn", "mid").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><Horn geometry={midHorn} emitterGeometry={midGlow} y={.02} frontZ={front} materials={materials} /><mesh geometry={box} position={[0, -.23, front + .012]} scale={[.28, .12, .06]} material={materials.throat} /></>; }
function Top({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-top", "high").body; const front = body.depth / 2 + .02; const emitters = [[-.28, .1], [0, .1], [.28, .1], [-.28, -.1], [0, -.1], [.28, -.1]]; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[body.width * .86, body.height * .65, .045]} material={materials.horn} />{emitters.map(([x, y], index) => <group key={index} position={[x, y, front + .03]}><mesh geometry={tweeter} scale={[.075, .075, 1]} material={materials.edge} /><mesh geometry={tweeter} position={[0, 0, .018]} scale={[.048, .048, 1]} material={materials.emitter} /></group>)}</>; }

export default function ReggaeSpeakerModel({ modelId, kind, activity, selected = false }: Props) { const materials = useReggaeMaterials(kind, activity); const model = getSpeakerModel(modelId, kind); return <group>{modelId === "reggae-scoop" && <Scoop materials={materials} />}{modelId === "reggae-kick" && <Kick materials={materials} />}{modelId === "reggae-mid-horn" && <MidHorn materials={materials} />}{modelId === "reggae-top" && <Top materials={materials} />}{selected && <mesh geometry={box} scale={[model.body.width * 1.018, model.body.height * 1.018, model.body.depth * 1.018]} material={selection} />}</group>; }
