/* Club Craft Reggae rule: warm painted plywood cabinets reveal frequency color only from horn throats and tweeter emitters, never from the cabinet shell. */
import * as THREE from "three";
import { useEffect, useMemo } from "react";
import { useThree } from "@react-three/fiber";
import type { SpeakerKind } from "@/hooks/useClubAudio";
import { getSpeakerModel, type SpeakerModelId } from "@/lib/speakerModels";

type Props = { modelId: SpeakerModelId; kind: SpeakerKind; activity: number; selected?: boolean };
const box = new THREE.BoxGeometry(1, 1, 1); const selection = new THREE.MeshBasicMaterial({ color: "#d5c2a8", transparent: true, opacity: .035, side: THREE.BackSide });
const LOW = new THREE.Color("#ff3b30"); const KICK = new THREE.Color("#ff9f0a"); const MID = new THREE.Color("#ffd60a"); const HIGH = new THREE.Color("#32d05b");
function hornGeometry(mouthWidth: number, mouthHeight: number, throatWidth: number, throatHeight: number, depth: number) { const positions = new Float32Array([-mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, mouthHeight / 2, 0, -mouthWidth / 2, mouthHeight / 2, 0, -throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, throatHeight / 2, -depth, -throatWidth / 2, throatHeight / 2, -depth]); const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3)); geometry.setIndex([0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7]); for (let index = 0; index < 4; index += 1) geometry.addGroup(index * 6, 6, index); geometry.computeVertexNormals(); return geometry; }
const scoopHorn = hornGeometry(1.18, .82, .2, .12, .7); const scoopGlow = hornGeometry(.76, .5, .1, .06, .55); const kickHorn = hornGeometry(1.12, .58, .2, .1, .48); const kickGlow = hornGeometry(.7, .34, .1, .055, .36); const midHorn = hornGeometry(.48, .46, .08, .06, .38); const midGlow = hornGeometry(.3, .27, .045, .032, .27); const topHorn = hornGeometry(.42, .22, .055, .032, .24); const topGlow = hornGeometry(.25, .12, .03, .018, .17);
const frameMaterial = new THREE.MeshStandardMaterial({ color: "#4b4032", roughness: .8, metalness: .01 });
const hornVoidMaterial = new THREE.MeshBasicMaterial({ color: "#040403", toneMapped: false });
const hornWallMaterials = ["#17130f", "#211c16", "#2b241b", "#0e0c09"].map((color) => new THREE.MeshStandardMaterial({ color, roughness: .92, metalness: 0, side: THREE.DoubleSide }));
function useReggaeMaterials(kind: SpeakerKind, activity: number) { const { invalidate } = useThree(); const materials = useMemo(() => ({ cabinet: new THREE.MeshStandardMaterial({ color: "#25231f", roughness: .91, metalness: 0 }), edge: new THREE.MeshStandardMaterial({ color: "#514536", roughness: .78, metalness: .02 }), horn: new THREE.MeshStandardMaterial({ color: "#242019", roughness: .88, side: THREE.DoubleSide }), emitter: new THREE.MeshStandardMaterial({ color: "#000000", emissive: "#000000", emissiveIntensity: 0, roughness: .65, side: THREE.DoubleSide, toneMapped: false }), throat: new THREE.MeshStandardMaterial({ color: "#050504", roughness: .94 }) }), []); useEffect(() => () => Object.values(materials).forEach((material) => material.dispose()), [materials]); useEffect(() => { const active = Math.pow(THREE.MathUtils.clamp(activity, 0, 1), .92); const color = kind === "sub" ? LOW : kind === "woofer" ? KICK : kind === "mid" ? MID : HIGH; materials.emitter.color.copy(color).multiplyScalar(active > 0 ? .1 + active * .9 : 0); materials.emitter.emissive.copy(color); materials.emitter.emissiveIntensity = active * (kind === "high" ? 1.1 : .96); invalidate(); }, [activity, invalidate, kind, materials]); return materials; }
function Horn({ geometry, emitterGeometry, x = 0, y, frontZ, mouthWidth = .9, mouthHeight = .5, depth = .3, throatWidth = .08, throatHeight = .05, materials }: { geometry: THREE.BufferGeometry; emitterGeometry: THREE.BufferGeometry; x?: number; y: number; frontZ: number; mouthWidth?: number; mouthHeight?: number; depth?: number; throatWidth?: number; throatHeight?: number; materials: ReturnType<typeof useReggaeMaterials> }) { void emitterGeometry; const visualDepth = THREE.MathUtils.clamp(depth * .12, .035, .065); const innerWidth = THREE.MathUtils.lerp(throatWidth, mouthWidth, .42); const innerHeight = THREE.MathUtils.lerp(throatHeight, mouthHeight, .42); return <group position={[x, y, frontZ]}><mesh geometry={box} position={[0, 0, -.004]} scale={[mouthWidth * .91, mouthHeight * .84, .018]} material={hornVoidMaterial} /><mesh geometry={geometry} position={[0, 0, visualDepth + .006]} scale={[1, 1, visualDepth / depth]} material={hornWallMaterials} /><mesh geometry={box} position={[0, 0, .012]} scale={[throatWidth, throatHeight, .022]} material={materials.emitter} /><HornRing width={innerWidth} height={innerHeight} z={visualDepth * .42} /></group>; }
function CabinetFrame({ width, height, front }: { width: number; height: number; front: number }) { const rail = .035; return <group><mesh geometry={box} position={[0, height / 2, front + .024]} scale={[width, rail, .045]} material={frameMaterial} /><mesh geometry={box} position={[0, -height / 2, front + .024]} scale={[width, rail, .045]} material={frameMaterial} /><mesh geometry={box} position={[-width / 2, 0, front + .024]} scale={[rail, height, .045]} material={frameMaterial} /><mesh geometry={box} position={[width / 2, 0, front + .024]} scale={[rail, height, .045]} material={frameMaterial} /></group>; }
function HornRing({ width, height, z }: { width: number; height: number; z: number }) { const rail = .022; return <group position={[0, 0, z]}><mesh geometry={box} position={[0, height / 2, 0]} scale={[width, rail, .026]} material={frameMaterial} /><mesh geometry={box} position={[0, -height / 2, 0]} scale={[width, rail, .026]} material={frameMaterial} /><mesh geometry={box} position={[-width / 2, 0, 0]} scale={[rail, height, .026]} material={frameMaterial} /><mesh geometry={box} position={[width / 2, 0, 0]} scale={[rail, height, .026]} material={frameMaterial} /></group>; }
function HornBack({ width, height, x = 0, y, front, materials }: { width: number; height: number; x?: number; y: number; front: number; materials: ReturnType<typeof useReggaeMaterials> }) { return <mesh geometry={box} position={[x, y, front + .006]} scale={[width, height, .035]} material={materials.throat} />; }
function HornBraces({ xs, y, height, front, horizontal = true }: { xs: number[]; y: number; height: number; front: number; horizontal?: boolean }) { return <group>{xs.map((x) => <mesh key={x} geometry={box} position={[x, y, front + .03]} scale={[.034, height, .045]} material={frameMaterial} />)}{horizontal && <mesh geometry={box} position={[0, y, front + .03]} scale={[Math.max(...xs.map(Math.abs), .45) * 2.35, .032, .045]} material={frameMaterial} />}</group>; }
function Scoop({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-scoop", "sub").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><mesh geometry={box} position={[0, .55, front + .012]} scale={[body.width * .84, .34, .05]} material={materials.throat} /><HornBack width={1.22} height={.86} y={-.31} front={front} materials={materials} /><CabinetFrame width={body.width * .92} height={body.height * .9} front={front} /><Horn geometry={scoopHorn} emitterGeometry={scoopGlow} y={-.31} frontZ={front + .04} mouthWidth={1.18} mouthHeight={.82} depth={.68} throatWidth={.12} throatHeight={.07} materials={materials} /><HornBraces xs={[-.31, .31]} y={-.31} height={.72} front={front + .045} /><mesh geometry={box} position={[0, -.31, front - .64]} scale={[.16, .1, .04]} material={materials.throat} /></>; }
function Kick({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-kick", "woofer").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><HornBack width={1.16} height={.62} y={0} front={front} materials={materials} /><CabinetFrame width={body.width * .91} height={body.height * .82} front={front} /><Horn geometry={kickHorn} emitterGeometry={kickGlow} y={0} frontZ={front + .04} mouthWidth={1.12} mouthHeight={.58} depth={.48} throatWidth={.11} throatHeight={.06} materials={materials} /><HornBraces xs={[-.3, .3]} y={0} height={.48} front={front + .045} /></>; }
function MidHorn({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-mid-horn", "mid").body; const front = body.depth / 2 + .014; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><HornBack width={.5} height={.48} x={-.25} y={.01} front={front} materials={materials} /><HornBack width={.5} height={.48} x={.25} y={.01} front={front} materials={materials} /><CabinetFrame width={body.width * .91} height={body.height * .82} front={front} /><Horn geometry={midHorn} emitterGeometry={midGlow} x={-.25} y={.01} frontZ={front + .04} mouthWidth={.48} mouthHeight={.46} depth={.38} throatWidth={.08} throatHeight={.06} materials={materials} /><Horn geometry={midHorn} emitterGeometry={midGlow} x={.25} y={.01} frontZ={front + .04} mouthWidth={.48} mouthHeight={.46} depth={.38} throatWidth={.08} throatHeight={.06} materials={materials} /><HornBraces xs={[0]} y={.01} height={.5} front={front + .045} horizontal={false} /></>; }
function Top({ materials }: { materials: ReturnType<typeof useReggaeMaterials> }) { const body = getSpeakerModel("reggae-top", "high").body; const front = body.depth / 2 + .02; return <><mesh geometry={box} scale={[body.width, body.height, body.depth]} material={materials.cabinet} /><HornBack width={.44} height={.24} x={-.23} y={0} front={front} materials={materials} /><HornBack width={.44} height={.24} x={.23} y={0} front={front} materials={materials} /><CabinetFrame width={body.width * .91} height={body.height * .76} front={front} /><Horn geometry={topHorn} emitterGeometry={topGlow} x={-.23} y={0} frontZ={front + .04} mouthWidth={.42} mouthHeight={.22} depth={.24} throatWidth={.055} throatHeight={.032} materials={materials} /><Horn geometry={topHorn} emitterGeometry={topGlow} x={.23} y={0} frontZ={front + .04} mouthWidth={.42} mouthHeight={.22} depth={.24} throatWidth={.055} throatHeight={.032} materials={materials} /><HornBraces xs={[0]} y={0} height={.26} front={front + .045} horizontal={false} /></>; }

export default function ReggaeSpeakerModel({ modelId, kind, activity, selected = false }: Props) { const materials = useReggaeMaterials(kind, activity); const model = getSpeakerModel(modelId, kind); return <group>{modelId === "reggae-scoop" && <Scoop materials={materials} />}{modelId === "reggae-kick" && <Kick materials={materials} />}{modelId === "reggae-mid-horn" && <MidHorn materials={materials} />}{modelId === "reggae-top" && <Top materials={materials} />}{selected && <mesh geometry={box} scale={[model.body.width * 1.018, model.body.height * 1.018, model.body.depth * 1.018]} material={selection} />}</group>; }
