import * as THREE from "three";
import { useEffect, useMemo } from "react";
import { useThree } from "@react-three/fiber";
import type { SpeakerKind } from "@/hooks/useClubAudio";
import { getSpeakerModel, type SpeakerModelId, type SpeakerVisualVariant } from "@/lib/speakerModels";
import type { SpeakerBandActivity } from "@/lib/bandActivity";

type Props = { modelId: SpeakerModelId; kind: SpeakerKind; activity: number; bandActivity?: SpeakerBandActivity; selected?: boolean };
const box = new THREE.BoxGeometry(1, 1, 1);
const woofer = new THREE.CylinderGeometry(1, 1, .035, 24); woofer.rotateX(Math.PI / 2);
const ring = new THREE.TorusGeometry(1, .08, 6, 24);
const flare = new THREE.ConeGeometry(1, .42, 4, 1, true); flare.rotateX(Math.PI / 2);
const selection = new THREE.MeshBasicMaterial({ color: "#d5c2a8", transparent: true, opacity: .035, side: THREE.BackSide });
const shapes = [0, 1, 2, 3, 4];

function materialColor(variant: SpeakerVisualVariant) { return variant === "hifi" ? "#76583c" : variant === "freeparty" ? "#64696d" : "#70767b"; }
function useSceneMaterials(variant: SpeakerVisualVariant, kind: SpeakerKind, activity: number) {
  const materials = useMemo(() => ({ cabinet: new THREE.MeshStandardMaterial({ color: materialColor(variant), roughness: variant === "hifi" ? .55 : .86, metalness: variant === "festival" ? .08 : .03 }), baffle: new THREE.MeshStandardMaterial({ color: "#41474c", roughness: .88 }), trim: new THREE.MeshStandardMaterial({ color: variant === "hifi" ? "#bd9366" : "#a2a8ad", roughness: .55, metalness: .2 }), emitter: new THREE.MeshStandardMaterial({ color: "#353b40", emissive: "#000000", emissiveIntensity: 0, toneMapped: false, roughness: .68 }) }), [variant]);
  const { invalidate } = useThree();
  useEffect(() => () => Object.values(materials).forEach((material) => material.dispose()), [materials]);
  useEffect(() => { const active = Math.pow(THREE.MathUtils.clamp(activity, 0, 1), 1.15); const color = kind === "sub" || kind === "woofer" ? new THREE.Color("#ff4b3a") : kind === "mid" ? new THREE.Color("#f3c849") : new THREE.Color("#45d86a"); materials.emitter.color.copy(color).multiplyScalar(active); materials.emitter.emissive.copy(color); materials.emitter.emissiveIntensity = active * .75; invalidate(); }, [activity, invalidate, kind, materials]);
  return materials;
}

function Driver({ x = 0, y = 0, z, size, materials }: { x?: number; y?: number; z: number; size: number; materials: ReturnType<typeof useSceneMaterials> }) { return <group position={[x, y, z]}><mesh geometry={ring} scale={[size, size, 1]} material={materials.trim} /><mesh geometry={woofer} position={[0, 0, .025]} scale={[size * .83, size * .83, 1]} material={materials.emitter} /></group>; }
function FreeParty({ id, dims, materials }: { id: SpeakerModelId; dims: [number, number, number]; materials: ReturnType<typeof useSceneMaterials> }) { const [w, h, d] = dims; const front = d / 2 + .025; if (id === "freeparty-wbin") return <><mesh geometry={box} scale={dims} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .88, h * .76, .04]} material={materials.baffle} /><mesh geometry={box} position={[-w * .22, 0, front + .03]} rotation={[0, 0, -.55]} scale={[w * .1, h * .7, .05]} material={materials.trim} /><mesh geometry={box} position={[w * .22, 0, front + .03]} rotation={[0, 0, .55]} scale={[w * .1, h * .7, .05]} material={materials.trim} /><Driver y={0} z={front + .06} size={Math.min(w, h) * .24} materials={materials} /></>;
  return <><mesh geometry={box} scale={dims} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .88, h * .76, .04]} material={materials.baffle} />{id === "freeparty-kick-horn" && <Driver y={-.08} z={front + .06} size={Math.min(w, h) * .28} materials={materials} />}<mesh geometry={flare} position={[0, id === "freeparty-kick-horn" ? .12 : 0, front + .08]} scale={[w * .32, h * .3, 1]} material={materials.emitter} /></>;
}
function Festival({ id, dims, materials }: { id: SpeakerModelId; dims: [number, number, number]; materials: ReturnType<typeof useSceneMaterials> }) { const [w, h, d] = dims; const front = d / 2 + .025; if (id === "festival-line-array") return <group>{shapes.map((index) => <group key={index} position={[0, h / 2 - .29 - index * .58, 0]} rotation={[-.055 * index, 0, 0]}><mesh geometry={box} scale={[w, .5, d]} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .84, .32, .04]} material={materials.baffle} /><mesh geometry={flare} position={[0, 0, front + .05]} scale={[w * .25, .12, 1]} material={materials.emitter} /></group>)}<mesh geometry={box} position={[0, h / 2 + .12, 0]} scale={[w * .72, .05, d * .6]} material={materials.trim} /></group>;
  return <><mesh geometry={box} scale={dims} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .88, h * .74, .04]} material={materials.baffle} />{id === "festival-sub" ? <><Driver x={-w * .23} z={front + .06} size={h * .28} materials={materials} /><Driver x={w * .23} z={front + .06} size={h * .28} materials={materials} /></> : <mesh geometry={flare} position={[0, 0, front + .07]} scale={[w * .28, h * .25, 1]} material={materials.emitter} />}</>;
}
function HiFi({ id, dims, materials }: { id: SpeakerModelId; dims: [number, number, number]; materials: ReturnType<typeof useSceneMaterials> }) { const [w, h, d] = dims; const front = d / 2 + .03; return <><mesh geometry={box} scale={dims} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .88, h * .8, .04]} material={materials.trim} />{id === "hifi-woofer" && <Driver z={front + .07} size={Math.min(w, h) * .33} materials={materials} />}{id === "hifi-mid-horn" && <mesh geometry={flare} position={[0, 0, front + .09]} scale={[w * .34, h * .4, 1]} material={materials.emitter} />}{id === "hifi-tweeter" && <><mesh geometry={flare} position={[-w * .19, 0, front + .08]} scale={[w * .14, h * .25, 1]} material={materials.emitter} /><mesh geometry={flare} position={[w * .19, 0, front + .08]} scale={[w * .14, h * .25, 1]} material={materials.emitter} /></>}</>;
}
function Steppers({ id, dims, materials }: { id: SpeakerModelId; dims: [number, number, number]; materials: ReturnType<typeof useSceneMaterials> }) { const [w, h, d] = dims; const front = d / 2 + .025; return <><mesh geometry={box} scale={dims} material={materials.cabinet} /><mesh geometry={box} position={[0, 0, front]} scale={[w * .88, h * .75, .04]} material={materials.baffle} />{id === "steppers-reflex-sub" ? <><Driver x={-w * .22} z={front + .06} size={h * .24} materials={materials} /><Driver x={w * .22} z={front + .06} size={h * .24} materials={materials} /></> : id === "steppers-kick" ? <mesh geometry={flare} position={[0, 0, front + .08]} scale={[w * .3, h * .3, 1]} material={materials.emitter} /> : <><Driver y={id === "steppers-mid" ? -.12 : 0} z={front + .06} size={h * .23} materials={materials} /><mesh geometry={flare} position={[0, id === "steppers-mid" ? h * .2 : 0, front + .08]} scale={[w * .24, h * .2, 1]} material={materials.emitter} /></>}</>;
}

export default function SceneSpeakerModel({ modelId, kind, activity, bandActivity, selected = false }: Props) { const model = getSpeakerModel(modelId, kind); const dims: [number, number, number] = [model.body.width, model.body.height, model.body.depth]; const bands = bandActivity ?? { overall: activity, low: activity, mid: activity, high: activity }; const emitterActivity = kind === "sub" || kind === "woofer" ? bands.low : kind === "mid" ? bands.mid : kind === "high" ? bands.high : bands.overall; const materials = useSceneMaterials(model.visual.variant, kind, emitterActivity); return <group>{model.family === "freeparty" && <FreeParty id={modelId} dims={dims} materials={materials} />}{model.family === "festival" && <Festival id={modelId} dims={dims} materials={materials} />}{model.family === "hifi" && <HiFi id={modelId} dims={dims} materials={materials} />}{model.family === "steppers" && <Steppers id={modelId} dims={dims} materials={materials} />}{selected && <mesh geometry={box} scale={[dims[0] * 1.02, dims[1] * 1.02, dims[2] * 1.02]} material={selection} />}</group>; }
