/**
 * Underground emergence: almost-black club space where physical speaker cabinets become visible through real audio activity.
 * This file remains visual only; selection, grid snapping, dragging and audio behavior are controlled by the shared ClubScene.
 */
import { Canvas, type ThreeEvent, useThree } from "@react-three/fiber";
import { ContactShadows, Grid, RoundedBox } from "@react-three/drei";
import * as THREE from "three";
import { useEffect, useRef } from "react";
import type { ClubListener, ClubSpeaker, Position3D, SpeakerKind } from "@/hooks/useClubAudio";

type Point = { x: number; y: number };
type DragTarget = { type: "speaker"; id: string } | { type: "listener" } | null;
type Props = { speakers: ClubSpeaker[]; listener: ClubListener; selectedSpeakerId: string; sourceColor?: string; signalActive?: boolean; onSpeakerSelect: (id: string) => void; onSpeakerMove: (id: string, position: Point) => void; onListenerMove: (position: Point) => void };

const roomWidth = 13; const roomDepth = 8;
const toWorld = (point: Pick<Position3D, "x" | "y">): [number, number, number] => [(point.x - .5) * roomWidth, 0, (point.y - .5) * roomDepth];
const toPoint = (position: THREE.Vector3): Point => ({ x: Math.max(.07, Math.min(.93, position.x / roomWidth + .5)), y: Math.max(.07, Math.min(.93, position.z / roomDepth + .5)) });
const typeStyles: Record<SpeakerKind, { body: [number, number, number]; drivers: Array<[number, number]>; horn?: boolean }> = { sub: { body: [1.55, .86, 1.2], drivers: [[0, 0]] }, woofer: { body: [1.72, .72, .82], drivers: [[-.38, 0], [.38, 0]] }, full: { body: [.7, 1.78, .74], drivers: [[0, -.37], [0, .38]] }, mid: { body: [.7, .74, .66], drivers: [[0, 0]] }, high: { body: [.76, .52, .68], drivers: [[0, 0]], horn: true } };

function Driver({ x, y, depth, size, horn, activity }: { x: number; y: number; depth: number; size: number; horn?: boolean; activity: number }) {
  const glow = activity * .56;
  if (horn) return <group position={[x, y, depth / 2 + .07]} rotation={[Math.PI / 2, 0, 0]}><mesh><coneGeometry args={[size * 1.35, .28, 4]} /><meshStandardMaterial color="#141510" roughness={.82} emissive="#d9c1a2" emissiveIntensity={glow} /></mesh><mesh position={[0, -.15, 0]}><cylinderGeometry args={[size * .23, size * .23, .02, 18]} /><meshStandardMaterial color="#050604" /></mesh></group>;
  return <group position={[x, y, depth / 2 + .05]} rotation={[Math.PI / 2, 0, 0]}><mesh><cylinderGeometry args={[size, size, .08, 24]} /><meshStandardMaterial color="#10110f" roughness={.66} emissive="#e2c7a6" emissiveIntensity={glow} /></mesh><mesh position={[0, 0, .046]}><cylinderGeometry args={[size * .68, size * .68, .014, 24]} /><meshStandardMaterial color="#030403" roughness={.52} /></mesh></group>;
}

function PrintedLayers({ width, height, depth }: { width: number; height: number; depth: number }) { return <group position={[0, 0, depth / 2 + .01]}>{Array.from({ length: Math.max(3, Math.floor(height / .16)) }, (_, index) => <mesh key={index} position={[0, -height / 2 + .11 + index * .16, 0]}><boxGeometry args={[width * .92, .012, .014]} /><meshStandardMaterial color="#726d63" transparent opacity={.06} /></mesh>)}</group>; }

function SpeakerObject({ speaker, selected, onSelect, onDragStart, onDragMove, onDragEnd }: { speaker: ClubSpeaker; selected: boolean; onSelect: () => void; onDragStart: (event: ThreeEvent<PointerEvent>) => void; onDragMove: (event: ThreeEvent<PointerEvent>) => void; onDragEnd: () => void }) {
  const style = typeStyles[speaker.kind]; const [width, height, depth] = style.body; const [x, , z] = toWorld(speaker.position); const lift = speaker.position.z * .68; const activity = speaker.activity; const driverSize = speaker.kind === "sub" ? .37 : speaker.kind === "woofer" ? .21 : speaker.kind === "high" ? .2 : .18;
  return <group position={[x, height / 2 + lift, z]} onPointerDown={(event) => { event.stopPropagation(); onSelect(); onDragStart(event); }} onPointerMove={(event) => { event.stopPropagation(); onDragMove(event); }} onPointerUp={(event) => { event.stopPropagation(); onDragEnd(); }}>
    {lift > .02 && <mesh position={[0, -height / 2 - lift / 2, 0]}><boxGeometry args={[.022, lift, .022]} /><meshStandardMaterial color="#242520" roughness={.9} /></mesh>}
    {selected && <mesh position={[0, -height / 2 - lift + .012, 0]} rotation={[-Math.PI / 2, 0, 0]}><ringGeometry args={[Math.max(width, depth) * .7, Math.max(width, depth) * .715, 40]} /><meshBasicMaterial color="#c6c3b8" transparent opacity={.15} side={THREE.DoubleSide} /></mesh>}
    <pointLight color="#e4c6a5" intensity={activity * 1.7} distance={2.5} decay={2} position={[0, .05, depth / 2 + .4]} />
    {activity > .02 && <mesh position={[0, 0, depth / 2 + .09]} rotation={[Math.PI / 2, 0, 0]}><coneGeometry args={[Math.max(width, height) * (.32 + activity * .35), .6 + activity * .75, 28, 1, true]} /><meshBasicMaterial color="#ddc3a4" transparent opacity={activity * .045} blending={THREE.AdditiveBlending} depthWrite={false} side={THREE.DoubleSide} /></mesh>}
    <RoundedBox args={[width, height, depth]} radius={.055} smoothness={2} castShadow receiveShadow><meshStandardMaterial color="#121310" roughness={.74} metalness={.05} emissive="#c5a98c" emissiveIntensity={activity * .18} /></RoundedBox>
    <RoundedBox args={[width * .86, height * .82, .035]} position={[0, 0, depth / 2 + .021]} radius={.026} smoothness={2} castShadow><meshStandardMaterial color="#050604" roughness={.83} /></RoundedBox>
    <PrintedLayers width={width} height={height} depth={depth} />
    {style.drivers.map(([driverX, driverY]) => <Driver key={`${driverX}-${driverY}`} x={driverX} y={driverY} depth={depth} size={driverSize} horn={style.horn} activity={activity} />)}
    <mesh position={[0, -height / 2 - .045, 0]} castShadow><boxGeometry args={[width * 1.08, .09, depth * 1.08]} /><meshStandardMaterial color="#0a0b09" roughness={.78} /></mesh>
  </group>;
}

function ListenerObject({ listener, onDragStart, onDragMove, onDragEnd }: { listener: ClubListener; onDragStart: (event: ThreeEvent<PointerEvent>) => void; onDragMove: (event: ThreeEvent<PointerEvent>) => void; onDragEnd: () => void }) { const [x, , z] = toWorld(listener.position); return <group position={[x, .14, z]} onPointerDown={(event) => { event.stopPropagation(); onDragStart(event); }} onPointerMove={(event) => { event.stopPropagation(); onDragMove(event); }} onPointerUp={(event) => { event.stopPropagation(); onDragEnd(); }}><mesh position={[0, -.126, 0]} rotation={[-Math.PI / 2, 0, 0]}><ringGeometry args={[.38, .39, 48]} /><meshBasicMaterial color="#a69f91" transparent opacity={.12} side={THREE.DoubleSide} /></mesh><mesh castShadow><cylinderGeometry args={[.16, .22, .16, 20]} /><meshStandardMaterial color="#22231f" roughness={.64} /></mesh><mesh position={[0, .19, 0]} castShadow><sphereGeometry args={[.115, 18, 16]} /><meshStandardMaterial color="#bbb4a6" emissive="#6d665c" emissiveIntensity={.16} roughness={.72} /></mesh></group>; }

function UndergroundHaze() { return <group>{[[-3.8, .35, -1.6, 4.8, .7], [2.9, .55, .8, 5.8, .9], [0, 1.4, -2.7, 7.4, 1.2]].map(([x, y, z, width, height], index) => <mesh key={index} position={[x, y, z]} rotation={[-Math.PI / 2 + .2, 0, index === 1 ? -.18 : .12]}><planeGeometry args={[width, height]} /><meshBasicMaterial color="#a4a29a" transparent opacity={.018 + index * .006} depthWrite={false} side={THREE.DoubleSide} /></mesh>)}</group>; }
function ResponsiveFloorCamera() { const { camera, size } = useThree(); useEffect(() => { const orthographic = camera as THREE.OrthographicCamera; orthographic.position.set(0, 14, 3.2); orthographic.zoom = size.width < 760 ? 46 : 92; orthographic.lookAt(0, 0, 0); orthographic.updateProjectionMatrix(); }, [camera, size.width]); return null; }

function RoomScene(props: Props) {
  const drag = useRef<DragTarget>(null); const update = (event: ThreeEvent<PointerEvent>) => { if (!drag.current) return; const point = toPoint(event.point); if (drag.current.type === "speaker") props.onSpeakerMove(drag.current.id, point); else props.onListenerMove(point); }; const stop = () => { drag.current = null; };
  const selected = props.speakers.find((speaker) => speaker.id === props.selectedSpeakerId); const signalEnd = selected ? toWorld(selected.position) : [0, 0, 0]; const listenerWorld = toWorld(props.listener.position); const sourcePoint = new THREE.Vector3(0, .06, -.7); const speakerPoint = new THREE.Vector3(signalEnd[0], .06, signalEnd[2]); const listenerPoint = new THREE.Vector3(listenerWorld[0], .06, listenerWorld[2]);
  return <><ambientLight intensity={.11} /><directionalLight castShadow position={[4, 9, 5]} intensity={.28} color="#b7aa9a" shadow-mapSize-width={1024} shadow-mapSize-height={1024} /><directionalLight position={[-5, 6, -4]} intensity={.045} color="#817b72" /><mesh rotation={[-Math.PI / 2, 0, 0]} receiveShadow onPointerMove={update} onPointerUp={stop}><planeGeometry args={[roomWidth * 1.9, roomDepth * 1.9]} /><meshStandardMaterial color="#080909" roughness={.98} /></mesh><Grid args={[roomWidth, roomDepth]} cellSize={roomWidth / 12} cellThickness={.08} cellColor="#171817" sectionSize={roomWidth} sectionThickness={.12} sectionColor="#22231f" fadeDistance={30} fadeStrength={1.2} position={[0, .012, 0]} /><UndergroundHaze /><group position={[0, .09, -3.3]}><mesh castShadow><boxGeometry args={[1.75, .18, .55]} /><meshStandardMaterial color="#111210" roughness={.86} /></mesh><mesh position={[0, .095, 0]}><boxGeometry args={[1.45, .014, .34]} /><meshStandardMaterial color="#292922" roughness={.9} /></mesh></group><mesh position={[0, .02, -.7]} rotation={[-Math.PI / 2, 0, 0]}><ringGeometry args={[.22, .227, 36]} /><meshBasicMaterial color={props.signalActive ? "#d64b35" : "#343530"} transparent opacity={props.signalActive ? .35 : .1} side={THREE.DoubleSide} /></mesh><mesh position={[0, .045, -.7]}><sphereGeometry args={[.065, 20, 16]} /><meshStandardMaterial color={props.signalActive ? "#d64b35" : "#242522"} emissive={props.signalActive ? "#8f2e22" : "#000000"} emissiveIntensity={props.signalActive ? .3 : 0} roughness={.62} /></mesh>{selected && props.signalActive && <><mesh><tubeGeometry args={[new THREE.CatmullRomCurve3([sourcePoint, new THREE.Vector3(sourcePoint.x, .08, (sourcePoint.z + speakerPoint.z) / 2), speakerPoint]), 24, .005, 6, false]} /><meshBasicMaterial color="#d64b35" transparent opacity={.32} /></mesh><mesh><tubeGeometry args={[new THREE.CatmullRomCurve3([speakerPoint, new THREE.Vector3((speakerPoint.x + listenerPoint.x) / 2, .04, (speakerPoint.z + listenerPoint.z) / 2), listenerPoint]), 24, .004, 6, false]} /><meshBasicMaterial color="#d64b35" transparent opacity={.16} /></mesh></>}{props.speakers.map((speaker) => <SpeakerObject key={speaker.id} speaker={speaker} selected={speaker.id === props.selectedSpeakerId} onSelect={() => props.onSpeakerSelect(speaker.id)} onDragStart={() => { drag.current = { type: "speaker", id: speaker.id }; }} onDragMove={update} onDragEnd={stop} />)}<ListenerObject listener={props.listener} onDragStart={() => { drag.current = { type: "listener" }; }} onDragMove={update} onDragEnd={stop} /><ContactShadows position={[0, .001, 0]} opacity={.68} scale={14} blur={2.8} far={6} color="#000000" /></>;
}

export default function ClubFloor3D(props: Props) { return <div className="club-floor-3d"><Canvas orthographic shadows camera={{ position: [0, 14, 3.2], zoom: 92 }} dpr={[1, 1.5]} gl={{ antialias: true, alpha: true }}><color attach="background" args={["#050606"]} /><ResponsiveFloorCamera /><RoomScene {...props} /></Canvas><div className="spatial-stage-anchor"><i />stage</div><div className="spatial-scale-anchor"><i />0&nbsp;&nbsp;&nbsp;&nbsp;3&nbsp;&nbsp;&nbsp;&nbsp;6 m</div></div>; }
