/*
 * Club Craft SIDE rule — the named Listener is a CSS human silhouette; the booth remains a non-interactive scene object.
 * Pointer drag edits depth (Y) and height (Z) only; X remains untouched in this projection.
 */
import { useEffect, useRef } from "react";
import { Trash2 } from "lucide-react";
import type { ClubListener, ClubSpeaker, SpeakerKind } from "@/hooks/useClubAudio";
import { exceedsDragThreshold, resolveStackRootId } from "@/lib/speakerInteraction";
import { SCENE_VERTICAL_METERS, speakerBodyForSpeaker } from "@/lib/speakerDimensions";
import { createStackResolver, STACK_ROOM_METERS } from "@/lib/speakerStacking";
import { blockDimensions, createBlockResolver, type SupportBlock } from "@/lib/blockSupport";
import { ContextualSpeakerLabel } from "@/components/ContextualDiagramLabel";

type RotationCue = { speakerId: string; yaw: number } | null;
type Props = { speakers: ClubSpeaker[]; blocks: SupportBlock[]; activityBySpeaker: Readonly<Record<string, number>>; listener: ClubListener; selectedSpeakerId: string; canRemove: boolean; rotationCue?: RotationCue; onSpeakerSelect: (id: string) => void; onSpeakerRemove: (id: string) => void; onSpeakerMove: (id: string, position: { y: number }) => void };
const clamp = (value: number) => Math.max(.04, Math.min(.96, value));

export default function SideScene({ speakers, blocks, activityBySpeaker, listener, selectedSpeakerId, canRemove, rotationCue, onSpeakerSelect, onSpeakerRemove, onSpeakerMove }: Props) {
  const sceneRef = useRef<HTMLDivElement>(null); const dragRef = useRef<{ id: string; rootId: string; startedAt: { x: number; y: number }; pointerType: string; offset: { x: number; y: number }; didMove: boolean } | null>(null); const rectRef = useRef<DOMRect | null>(null); const pendingRef = useRef<{ x: number; y: number } | null>(null); const frameRef = useRef<number | null>(null); const stackResolver = createStackResolver(speakers); const blockResolver = createBlockResolver(blocks);
  const flush = () => { frameRef.current = null; const active = dragRef.current; const rect = rectRef.current; const point = pendingRef.current; pendingRef.current = null; if (!active || !rect || !point) return; if (!active.didMove) { if (!exceedsDragThreshold(active.startedAt, point, active.pointerType)) return; active.didMove = true; onSpeakerSelect(active.id); } onSpeakerMove(active.rootId, { y: clamp((point.x - rect.left - active.offset.x) / rect.width) }); };
  const update = (event: React.PointerEvent<HTMLDivElement>) => { if (!dragRef.current || !rectRef.current) return; pendingRef.current = { x: event.clientX, y: event.clientY }; if (frameRef.current === null) frameRef.current = requestAnimationFrame(flush); };
  const stop = (commitSelection = true) => { if (frameRef.current !== null) { cancelAnimationFrame(frameRef.current); flush(); } const active = dragRef.current; if (active && commitSelection && !active.didMove) onSpeakerSelect(active.id); dragRef.current = null; rectRef.current = null; pendingRef.current = null; };
  useEffect(() => () => { if (frameRef.current !== null) cancelAnimationFrame(frameRef.current); }, []);
  return <div ref={sceneRef} className="side-scene" onPointerMove={update} onPointerUp={() => stop()} onPointerCancel={() => stop(false)}>
    <div className="side-stage">WORK SURFACE</div><div className="side-floor" /><div className="side-depth">tabletop section</div>
    {blocks.map((block) => { const dimensions = blockDimensions(block); return <div key={block.id} className="side-block" style={{ left: `${blockResolver.getXY(block).y * 88 + 6}%`, bottom: `${blockResolver.getBottomMeters(block) / SCENE_VERTICAL_METERS * 74 + 9}%`, width: `${dimensions.width / STACK_ROOM_METERS.depth * 88}%`, height: `${dimensions.height / SCENE_VERTICAL_METERS * 74}%`, transform: `translate(-50%, 0) rotate(${(block.orientation?.yaw ?? 0) * 180 / Math.PI}deg)` }}><span>BLOCK</span></div>; })}
    {speakers.map((speaker, index) => { const stacked = Boolean(speaker.stackParentId); const xy = stackResolver.getXY(speaker); const centerMeters = stackResolver.getCenterMeters(speaker); const body = speakerBodyForSpeaker(speaker); const selected = speaker.id === selectedSpeakerId; return <div key={speaker.id} className={`side-speaker ${speaker.kind} ${selected ? "selected" : ""} ${stacked ? "stacked" : ""}`} style={{ left: `${xy.y * 88 + 6}%`, bottom: `${centerMeters / SCENE_VERTICAL_METERS * 74 + 9}%`, width: `${body.depth / STACK_ROOM_METERS.depth * 88}%`, height: `${body.height / SCENE_VERTICAL_METERS * 74}%`, marginLeft: `${((index % 3) - 1) * 2}px`, "--activity": activityBySpeaker[speaker.id] ?? 0, "--cabinet-color": speaker.cabinetColor ?? "#41474c" } as React.CSSProperties}><button className="side-speaker-drag" onPointerDown={(event) => { event.stopPropagation(); const rect = sceneRef.current?.getBoundingClientRect(); if (!rect) return; const rootId = resolveStackRootId(speakers, speaker.id); const currentX = rect.left + (xy.y * .88 + .06) * rect.width; const currentY = rect.top + rect.height * (1 - (centerMeters / SCENE_VERTICAL_METERS * .74 + .09)); dragRef.current = { id: speaker.id, rootId, startedAt: { x: event.clientX, y: event.clientY }, pointerType: event.pointerType, offset: { x: currentX - event.clientX, y: currentY - event.clientY }, didMove: false }; rectRef.current = rect; sceneRef.current?.setPointerCapture(event.pointerId); }} aria-label={`Select or move ${speaker.kind} speaker`}><i /><b /></button>{selected && <span className={`side-contextual-label ${xy.y > .68 ? "is-left" : ""}`}><ContextualSpeakerLabel speaker={speaker} stackCount={stackResolver.getSubtreeIds(resolveStackRootId(speakers, speaker.id)).size} supportOnBlock={Boolean(speaker.supportBlockId)} variant="side" yawCue={rotationCue?.speakerId === speaker.id ? rotationCue.yaw : undefined} /></span>}{selected && <button className="side-cabinet-delete" type="button" disabled={!canRemove} onPointerDown={(event) => { event.stopPropagation(); }} onClick={(event) => { event.stopPropagation(); if (canRemove) onSpeakerRemove(speaker.id); }} aria-label={`Delete ${speaker.label}`}><Trash2 size={13} /></button>}</div>; })}
    <div className="side-listener" style={{ left: `${listener.position.y * 88 + 6}%`, bottom: `${listener.position.z * 74 + 9}%` }} aria-label={`${listener.name}, listener position`}><span className="side-listener-name">{listener.name}</span><i className="side-human-head" /><i className="side-human-body" /><i className="side-human-leg side-human-leg-left" /><i className="side-human-leg side-human-leg-right" /></div>
  </div>;
}
