/** Club Craft System Response Editor — SVG rendering of actual type-filter + Custom EQ response. */
import { useMemo, useRef } from "react";
import type { ClubSpeaker } from "@/hooks/useClubAudio";
import { EQ_RANGES, type SpeakerEq } from "@/lib/speakerEq";
import { calculateCombinedMagnitudeDb, clamp, dbToY, findIntersections, frequencyToX, getSpeakerResponse, responseToPath, speakerFilters, xToFrequency, yToGainDb, type ResponsePoint } from "@/lib/responseCurve";

type Props = { speakers: ClubSpeaker[]; selectedSpeakerId: string; onSpeakerSelect: (id: string) => void; onEqChange: (id: string, eq: SpeakerEq) => void };
const WIDTH = 1000; const HEIGHT = 420; const PAD = { left: 54, right: 18, top: 18, bottom: 38 }; const PLOT_WIDTH = WIDTH - PAD.left - PAD.right; const PLOT_HEIGHT = HEIGHT - PAD.top - PAD.bottom;
const colors: Record<ClubSpeaker["kind"], string> = { sub: "#d94e42", woofer: "#d2813d", full: "#8b7a61", mid: "#c1a63e", high: "#4f9b66" };
const labels: Record<ClubSpeaker["kind"], string> = { sub: "SUB", woofer: "WOOFER", full: "FULL", mid: "MID", high: "HIGH" };
const x = (frequency: number) => PAD.left + frequencyToX(frequency, PLOT_WIDTH); const y = (db: number) => PAD.top + dbToY(db, PLOT_HEIGHT); const path = (response: ResponsePoint[]) => responseToPath(response.map((point) => ({ ...point, db: point.db })), PLOT_WIDTH, PLOT_HEIGHT).replaceAll(/([ML])([\d.]+),([\d.]+)/g, (_, command, px, py) => `${command}${Number(px) + PAD.left},${Number(py) + PAD.top}`);

function ticks() { return [20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000]; }
function qLabel(value: number) { return value.toFixed(1); }

export default function SpeakerResponseGraph({ speakers, selectedSpeakerId, onSpeakerSelect, onEqChange }: Props) {
  const svgRef = useRef<SVGSVGElement>(null); const dragRef = useRef<{ pointerId: number; band: "low" | "lowMid" | "highMid" | "high"; speakerId: string } | null>(null); const latestRef = useRef<{ x: number; y: number } | null>(null); const frameRef = useRef(0);
  const curves = useMemo(() => speakers.map((speaker, index) => ({ speaker, number: index + 1, response: getSpeakerResponse(speaker) })), [speakers]);
  const selected = curves.find((curve) => curve.speaker.id === selectedSpeakerId) ?? curves[0];
  const applyDrag = () => { frameRef.current = 0; const target = dragRef.current; const latest = latestRef.current; const svg = svgRef.current; if (!target || !latest || !svg) return; const rect = svg.getBoundingClientRect(); const plotX = clamp((latest.x - rect.left) * WIDTH / rect.width - PAD.left, 0, PLOT_WIDTH); const plotY = clamp((latest.y - rect.top) * HEIGHT / rect.height - PAD.top, 0, PLOT_HEIGHT); const speaker = speakers.find((item) => item.id === target.speakerId); if (!speaker) return; const ranges = EQ_RANGES[target.band]; const frequency = clamp(xToFrequency(plotX, PLOT_WIDTH), ranges.frequency[0], ranges.frequency[1]); const gainDb = yToGainDb(plotY, PLOT_HEIGHT); const eq = target.band === "low" || target.band === "high" ? { ...speaker.eq, [target.band]: { ...speaker.eq[target.band], frequency, gainDb } } : { ...speaker.eq, [target.band]: { ...speaker.eq[target.band], frequency, gainDb } }; onEqChange(speaker.id, eq); };
  const beginDrag = (event: React.PointerEvent<SVGCircleElement>, band: "low" | "lowMid" | "highMid" | "high") => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); dragRef.current = { pointerId: event.pointerId, band, speakerId: selected.speaker.id }; latestRef.current = { x: event.clientX, y: event.clientY }; if (!frameRef.current) frameRef.current = requestAnimationFrame(applyDrag); };
  const moveDrag = (event: React.PointerEvent<SVGSVGElement>) => { if (dragRef.current?.pointerId !== event.pointerId) return; latestRef.current = { x: event.clientX, y: event.clientY }; if (!frameRef.current) frameRef.current = requestAnimationFrame(applyDrag); };
  const endDrag = (event: React.PointerEvent<SVGSVGElement>) => { if (dragRef.current?.pointerId !== event.pointerId) return; if (frameRef.current) { cancelAnimationFrame(frameRef.current); applyDrag(); } dragRef.current = null; latestRef.current = null; };
  const selectedIntersections = selected ? curves.filter((curve) => curve.speaker.id !== selected.speaker.id).flatMap((curve) => findIntersections(selected.response, curve.response)).sort((a, b) => a.frequency - b.frequency).reduce<ResponsePoint[]>((kept, point) => kept.some((previous) => Math.abs(Math.log2(previous.frequency / point.frequency)) < .38) ? kept : [...kept, point], []).slice(0, 3) : [];
  const renderCurve = (curve: typeof curves[number]) => { const labelOffset = curve.speaker.id === selected?.speaker.id ? -10 : 7 + curve.number * 10; return <g key={curve.speaker.id} className={`response-curve-group ${curve.speaker.id === selected?.speaker.id ? "is-selected" : ""}`} onClick={() => onSpeakerSelect(curve.speaker.id)}><path d={path(curve.response)} className="response-curve" style={{ stroke: colors[curve.speaker.kind] }} /><path d={path(curve.response)} className="response-curve-hit" /><text x={x(curve.response[194].frequency) + 5} y={y(curve.response[194].db) + labelOffset} className="response-curve-number" style={{ fill: colors[curve.speaker.kind] }}>{curve.number}</text></g>; };
  const points = selected ? (["low", "lowMid", "highMid", "high"] as const).map((band) => { const filter = speakerFilters(selected.speaker); const bandValue = selected.speaker.eq[band]; return { band, label: band === "low" ? "L" : band === "lowMid" ? "LM" : band === "highMid" ? "HM" : "H", frequency: bandValue.frequency, db: calculateCombinedMagnitudeDb(filter, bandValue.frequency) }; }) : [];
  return <div className="response-graph-wrap"><svg ref={svgRef} className="speaker-response-graph" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} preserveAspectRatio="none" onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}>
    <g className="response-grid">{ticks().map((frequency) => <g key={frequency}><line x1={x(frequency)} x2={x(frequency)} y1={PAD.top} y2={PAD.top + PLOT_HEIGHT} /><text x={x(frequency)} y={HEIGHT - 10}>{frequency >= 1000 ? `${frequency / 1000}k` : frequency}</text></g>)}{[12, 6, 0, -6, -12, -24, -36, -48].map((db) => <g key={db} className={db === 0 ? "is-zero" : ""}><line x1={PAD.left} x2={PAD.left + PLOT_WIDTH} y1={y(db)} y2={y(db)} /><text x={PAD.left - 8} y={y(db) + 3}>{db > 0 ? `+${db}` : db}</text></g>)}</g>
    {curves.filter((curve) => curve.speaker.id !== selected?.speaker.id).map(renderCurve)}{selected && renderCurve(selected)}
    <g className="response-intersections">{selectedIntersections.map((point, index) => <g key={`${point.frequency}-${index}`} transform={`translate(${x(point.frequency)},${y(point.db)})`}><circle r="3.3" /><text x="5" y="-5">{Math.round(point.frequency)} Hz · {point.db.toFixed(1)} dB</text></g>)}</g>
    {points.map((point) => <g key={point.band} className="response-eq-point" transform={`translate(${x(point.frequency)},${y(point.db)})`}><circle r="7" onPointerDown={(event) => beginDrag(event, point.band)} /><text y="3">{point.label}</text></g>)}
  </svg><div className="response-legend">{curves.map((curve) => <button key={curve.speaker.id} className={curve.speaker.id === selected?.speaker.id ? "is-selected" : ""} onClick={() => onSpeakerSelect(curve.speaker.id)}><i style={{ background: colors[curve.speaker.kind] }} />{curve.number} {labels[curve.speaker.kind]}</button>)}</div></div>;
}
