/* Club Craft visual rule: physical PA miniatures use neutral matte surfaces; only recessed acoustic surfaces reveal restrained activity color. */
import * as THREE from "three";
import { useEffect, useMemo } from "react";
import { useThree } from "@react-three/fiber";
import type { SpeakerKind } from "@/hooks/useClubAudio";

type Props = { kind: SpeakerKind; activity: number; selected?: boolean; showHaze?: boolean; idleVisible?: boolean };
type Blueprint = { body: [number, number, number]; cabinet: THREE.BufferGeometry; edges: THREE.EdgesGeometry };
type SpeakerMaterials = { cabinet: THREE.MeshStandardMaterial; baffle: THREE.MeshStandardMaterial; hornShell: THREE.MeshStandardMaterial; hornEmitter: THREE.MeshStandardMaterial; wooferCone: THREE.MeshStandardMaterial; wooferEmitter: THREE.MeshStandardMaterial };
type HornProps = { geometry: THREE.BufferGeometry; glowGeometry?: THREE.BufferGeometry; x?: number; y: number; frontZ: number; mouthWidth: number; mouthHeight: number; throatWidth: number; throatHeight: number; depth: number; materials: SpeakerMaterials };

const passiveFrameMaterial = new THREE.MeshStandardMaterial({ color: "#353632", roughness: .78, metalness: .08 });
const passiveDetailMaterial = new THREE.MeshStandardMaterial({ color: "#171815", roughness: .88, metalness: .02 });
const passiveMetalMaterial = new THREE.MeshStandardMaterial({ color: "#696a64", roughness: .55, metalness: .18 });
const passiveFootMaterial = new THREE.MeshStandardMaterial({ color: "#1c1d1b", roughness: .9 });
const selectionMaterial = new THREE.MeshBasicMaterial({ color: "#d5c2a8", transparent: true, opacity: .028, side: THREE.BackSide });
const idleEdgeMaterial = new THREE.LineBasicMaterial({ color: "#666761", transparent: true, opacity: .3 });
const unitBox = new THREE.BoxGeometry(1, 1, 1);
const wooferMount = new THREE.CylinderGeometry(1, 1, .028, 24);
wooferMount.rotateX(Math.PI / 2);
const wooferSurround = new THREE.TorusGeometry(1, .11, 6, 24);
const dustCap = new THREE.SphereGeometry(1, 16, 10);
const fastenerHead = new THREE.CylinderGeometry(.027, .027, .014, 12);

function makeChamferCabinet(width: number, height: number, depth: number, taper = 0) { const top = width * (1 - taper); const shape = new THREE.Shape(); shape.moveTo(-width / 2, -height / 2); shape.lineTo(width / 2, -height / 2); shape.lineTo(top / 2, height / 2); shape.lineTo(-top / 2, height / 2); shape.closePath(); const geometry = new THREE.ExtrudeGeometry(shape, { depth, bevelEnabled: true, bevelThickness: .03, bevelSize: .024, bevelSegments: 1, curveSegments: 1 }); geometry.translate(0, 0, -depth / 2); geometry.computeVertexNormals(); return geometry; }
function makeHornFlare(mouthWidth: number, mouthHeight: number, throatWidth: number, throatHeight: number, depth: number) { const vertices = new Float32Array([-mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, mouthHeight / 2, 0, -mouthWidth / 2, mouthHeight / 2, 0, -throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, throatHeight / 2, -depth, -throatWidth / 2, throatHeight / 2, -depth]); const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(vertices, 3)); geometry.setIndex([0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7]); geometry.computeVertexNormals(); return geometry; }
function makeConcaveDisc(radius = 1, segments = 32, depth = .16) { const geometry = new THREE.CircleGeometry(radius, segments); const positions = geometry.attributes.position; for (let i = 0; i < positions.count; i += 1) { const x = positions.getX(i); const y = positions.getY(i); const r = Math.min(1, Math.sqrt(x * x + y * y) / radius); positions.setZ(i, -depth * Math.pow(1 - r, 1.6)); } positions.needsUpdate = true; geometry.computeVertexNormals(); return geometry; }

const foldedSubHorn = makeHornFlare(.86, .58, .22, .16, .3); const foldedSubHornGlow = makeHornFlare(.62, .4, .14, .09, .245);
const upperWooferHorn = makeHornFlare(.78, .32, .18, .09, .28); const upperWooferHornGlow = makeHornFlare(.57, .22, .12, .055, .22);
const lowerWooferHorn = makeHornFlare(.78, .44, .2, .13, .3); const lowerWooferHornGlow = makeHornFlare(.57, .31, .13, .08, .24);
const fullHorn = makeHornFlare(.76, .36, .16, .09, .31); const fullHornGlow = makeHornFlare(.56, .24, .11, .055, .255);
const midHorn = makeHornFlare(.56, .2, .12, .07, .19); const midHornGlow = makeHornFlare(.4, .13, .08, .042, .145);
const highHorn = makeHornFlare(.88, .38, .12, .08, .36); const highHornGlow = makeHornFlare(.65, .27, .08, .05, .29);
const concaveWooferCone = makeConcaveDisc(1, 32, .18); const concaveWooferGlow = makeConcaveDisc(1, 32, .145);
function makeBlueprint(body: [number, number, number], taper: number): Blueprint { const cabinet = makeChamferCabinet(...body, taper); return { body, cabinet, edges: new THREE.EdgesGeometry(cabinet, 14) }; }
const blueprints: Record<SpeakerKind, Blueprint> = { sub: makeBlueprint([2.36, .9, 1.4], .015), woofer: makeBlueprint([1.15, 1.5, 1.08], .04), full: makeBlueprint([1.1, 2, 1.08], .1), mid: makeBlueprint([.84, .88, .58], .035), high: makeBlueprint([1.08, .62, .72], .08) };

const LOW = new THREE.Color("#ff3b30"); const MID = new THREE.Color("#ffd60a"); const HIGH = new THREE.Color("#32d05b");
const neutralCabinetColor = new THREE.Color("#62635e"); const neutralBaffleColor = new THREE.Color("#30312d"); const neutralHornColor = new THREE.Color("#151613"); const neutralConeColor = new THREE.Color("#171815");
const speakerBandProfile: Record<SpeakerKind, { horn: number; woofer: number; hornGain: number; wooferGain: number }> = { sub: { horn: 0, woofer: 0, hornGain: .62, wooferGain: 0 }, woofer: { horn: .08, woofer: 0, hornGain: .58, wooferGain: 0 }, full: { horn: 1, woofer: 0, hornGain: .7, wooferGain: .62 }, mid: { horn: .5, woofer: .5, hornGain: .62, wooferGain: .5 }, high: { horn: 1, woofer: 1, hornGain: .78, wooferGain: 0 } };
function setFrequencyColor(target: THREE.Color, position: number) { const band = THREE.MathUtils.clamp(position, 0, 1); return band <= .5 ? target.copy(LOW).lerp(MID, band * 2) : target.copy(MID).lerp(HIGH, (band - .5) * 2); }
function createEmitterMaterial() { return new THREE.MeshStandardMaterial({ color: "#111111", roughness: .72, metalness: 0, emissive: "#000000", emissiveIntensity: 0, side: THREE.DoubleSide, toneMapped: false }); }
function createSpeakerMaterials(): SpeakerMaterials { return { cabinet: new THREE.MeshStandardMaterial({ color: neutralCabinetColor, roughness: .84, metalness: .02, emissive: "#000000" }), baffle: new THREE.MeshStandardMaterial({ color: neutralBaffleColor, roughness: .9, metalness: .01, emissive: "#000000" }), hornShell: new THREE.MeshStandardMaterial({ color: neutralHornColor, roughness: .79, metalness: .01, side: THREE.DoubleSide, emissive: "#000000" }), hornEmitter: createEmitterMaterial(), wooferCone: new THREE.MeshStandardMaterial({ color: neutralConeColor, roughness: .8, metalness: .01, side: THREE.DoubleSide, emissive: "#000000" }), wooferEmitter: createEmitterMaterial() }; }
function useSpeakerMaterials(kind: SpeakerKind, activity: number) { const materials = useMemo(createSpeakerMaterials, []); const { invalidate } = useThree(); useEffect(() => () => { Object.values(materials).forEach((material) => material.dispose()); }, [materials]); useEffect(() => { const active = Math.pow(THREE.MathUtils.clamp(activity, 0, 1), 1.18); const profile = speakerBandProfile[kind]; const hornColor = setFrequencyColor(new THREE.Color(), profile.horn); const wooferColor = setFrequencyColor(new THREE.Color(), profile.woofer); materials.cabinet.color.copy(neutralCabinetColor); materials.baffle.color.copy(neutralBaffleColor); materials.hornShell.color.copy(neutralHornColor); materials.wooferCone.color.copy(neutralConeColor); materials.cabinet.emissiveIntensity = 0; materials.baffle.emissiveIntensity = 0; materials.hornShell.emissiveIntensity = 0; materials.wooferCone.emissiveIntensity = 0; materials.hornEmitter.color.copy(hornColor).multiplyScalar(active); materials.wooferEmitter.color.copy(wooferColor).multiplyScalar(active); materials.hornEmitter.emissive.copy(hornColor); materials.wooferEmitter.emissive.copy(wooferColor); materials.hornEmitter.emissiveIntensity = active * profile.hornGain; materials.wooferEmitter.emissiveIntensity = active * profile.wooferGain; invalidate(); }, [activity, invalidate, kind, materials]); return materials; }

function createGlowTexture(size = 64) { const data = new Uint8Array(size * size * 4); for (let y = 0; y < size; y += 1) for (let x = 0; x < size; x += 1) { const nx = x / (size - 1) * 2 - 1; const ny = y / (size - 1) * 2 - 1; const alpha = Math.pow(Math.max(0, 1 - Math.sqrt(nx * nx + ny * ny)), 2.5); const index = (y * size + x) * 4; data[index] = 255; data[index + 1] = 255; data[index + 2] = 255; data[index + 3] = Math.round(alpha * 255); } const texture = new THREE.DataTexture(data, size, size, THREE.RGBAFormat); texture.needsUpdate = true; return texture; }
const sharedGlowTexture = createGlowTexture();
function LocalGlow({ color, activity, position, size }: { color: THREE.Color; activity: number; position: [number, number, number]; size: number }) { const material = useMemo(() => new THREE.SpriteMaterial({ map: sharedGlowTexture, transparent: true, depthWrite: false, depthTest: true, blending: THREE.AdditiveBlending }), []); useEffect(() => () => material.dispose(), [material]); useEffect(() => { material.color.copy(color); material.opacity = Math.pow(THREE.MathUtils.clamp(activity, 0, 1), 1.4) * .07; }, [activity, color, material]); const scale = size * (1 + activity * .05); return <sprite material={material} position={position} scale={[scale, scale, 1]} renderOrder={2} />; }
function CabinetFeet({ width, height, depth, count = 2 }: { width: number; height: number; depth: number; count?: number }) { const positions = count === 4 ? [[-.37, -.3], [.37, -.3], [-.37, .3], [.37, .3]] : [[-.34, .12], [.34, .12]]; return <group position={[0, -height / 2 - .05, 0]}>{positions.map(([x, z], index) => <mesh key={index} geometry={unitBox} position={[x * width, 0, z * depth]} scale={[.1, .1, .12]} material={passiveFootMaterial} />)}</group>; }
function CornerFasteners({ width, height, frontZ, inset = .08 }: { width: number; height: number; frontZ: number; inset?: number }) { return <>{[[-1, -1], [1, -1], [-1, 1], [1, 1]].map(([x, y], index) => <mesh key={index} geometry={fastenerHead} rotation={[Math.PI / 2, 0, 0]} position={[x * (width / 2 - inset), y * (height / 2 - inset), frontZ]} material={passiveMetalMaterial} />)}</>; }
function HornLip({ width, height }: { width: number; height: number }) { const thickness = .022; return <><mesh geometry={unitBox} position={[0, height / 2, .012]} scale={[width, thickness, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[0, -height / 2, .012]} scale={[width, thickness, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[-width / 2, 0, .012]} scale={[thickness, height, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[width / 2, 0, .012]} scale={[thickness, height, .028]} material={passiveFrameMaterial} /></>; }
function HornFlare({ geometry, glowGeometry, x = 0, y, frontZ, mouthWidth, mouthHeight, throatWidth, throatHeight, depth, materials }: HornProps) { void throatWidth; void throatHeight; void depth; return <group position={[x, y, frontZ]}><mesh geometry={geometry} material={materials.hornShell} /><HornLip width={mouthWidth} height={mouthHeight} />{glowGeometry && <mesh geometry={glowGeometry} position={[0, 0, -.018]} material={materials.hornEmitter} />}</group>; }
function WooferAssembly({ size, y, frontZ, materials }: { size: number; y: number; frontZ: number; materials: SpeakerMaterials }) { return <group position={[0, y, frontZ + .015]}><mesh geometry={wooferMount} scale={[size * 1.12, size * 1.12, 1]} material={materials.baffle} /><mesh geometry={wooferSurround} position={[0, 0, .012]} scale={[size, size, 1]} material={materials.baffle} /><mesh geometry={concaveWooferCone} position={[0, 0, .018]} scale={[size * .82, size * .82, 1]} material={materials.wooferCone} /><mesh geometry={concaveWooferGlow} position={[0, 0, .022]} scale={[size * .64, size * .64, 1]} material={materials.wooferEmitter} /><mesh geometry={dustCap} position={[0, 0, .026]} scale={[size * .16, size * .16, size * .05]} material={passiveDetailMaterial} /></group>; }
function ReflexPort({ x, y, frontZ, width, height }: { x: number; y: number; frontZ: number; width: number; height: number }) { return <mesh geometry={unitBox} position={[x, y, frontZ + .032]} scale={[width, height, .038]} material={passiveDetailMaterial} />; }
function FoldedHorn({ geometry, glowGeometry, x = 0, y, frontZ, mouthWidth, mouthHeight, throatWidth, throatHeight, depth, materials }: HornProps) { return <group><HornFlare geometry={geometry} glowGeometry={glowGeometry} x={x} y={y} frontZ={frontZ} mouthWidth={mouthWidth} mouthHeight={mouthHeight} throatWidth={throatWidth} throatHeight={throatHeight} depth={depth} materials={materials} /><mesh geometry={unitBox} position={[x, y, frontZ - depth - .035]} scale={[throatWidth * .55, throatHeight * .55, .028]} material={materials.hornEmitter} /></group>; }

function SubModel({ blueprint, materials, activity, haze }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><FoldedHorn geometry={foldedSubHorn} glowGeometry={foldedSubHornGlow} x={-.55} y={.01} frontZ={frontZ} mouthWidth={.86} mouthHeight={.58} throatWidth={.22} throatHeight={.16} depth={.3} materials={materials} /><FoldedHorn geometry={foldedSubHorn} glowGeometry={foldedSubHornGlow} x={.55} y={.01} frontZ={frontZ} mouthWidth={.86} mouthHeight={.58} throatWidth={.22} throatHeight={.16} depth={.3} materials={materials} /><mesh geometry={unitBox} position={[0, 0, frontZ + .012]} scale={[.04, height * .65, .036]} material={passiveFrameMaterial} /><CornerFasteners width={width * .88} height={height * .76} frontZ={frontZ + .022} inset={.06} /><CabinetFeet width={width} height={height} depth={depth} count={4} />{haze && <LocalGlow color={LOW} activity={activity} position={[0, .01, frontZ + .02]} size={.92} />}</>; }
function WooferModel({ blueprint, materials, activity, haze }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><FoldedHorn geometry={upperWooferHorn} glowGeometry={upperWooferHornGlow} y={.38} frontZ={frontZ} mouthWidth={.78} mouthHeight={.32} throatWidth={.18} throatHeight={.09} depth={.28} materials={materials} /><FoldedHorn geometry={lowerWooferHorn} glowGeometry={lowerWooferHornGlow} y={-.36} frontZ={frontZ} mouthWidth={.78} mouthHeight={.44} throatWidth={.2} throatHeight={.13} depth={.3} materials={materials} /><mesh geometry={unitBox} position={[0, .02, frontZ + .012]} scale={[width * .7, .038, .036]} material={passiveDetailMaterial} /><CornerFasteners width={width * .86} height={height * .85} frontZ={frontZ + .022} /><CabinetFeet width={width} height={height} depth={depth} />{haze && <LocalGlow color={LOW} activity={activity} position={[0, -.35, frontZ + .02]} size={.58} />}</>; }
function FullModel({ blueprint, materials, activity, haze }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <group rotation={[-.04, 0, 0]}><mesh geometry={unitBox} scale={[width, height, depth]} material={materials.cabinet} /><HornFlare geometry={fullHorn} glowGeometry={fullHornGlow} y={.56} frontZ={frontZ} mouthWidth={.76} mouthHeight={.36} throatWidth={.16} throatHeight={.09} depth={.31} materials={materials} /><WooferAssembly size={.26} y={-.08} frontZ={frontZ} materials={materials} /><ReflexPort x={-.24} y={-.72} frontZ={frontZ + .02} width={.17} height={.055} /><ReflexPort x={.24} y={-.72} frontZ={frontZ + .02} width={.17} height={.055} /><CornerFasteners width={width * .84} height={height * .85} frontZ={frontZ + .023} /><CabinetFeet width={width} height={height} depth={depth} />{haze && <><LocalGlow color={LOW} activity={activity} position={[0, -.08, frontZ + .024]} size={.34} /><LocalGlow color={HIGH} activity={activity} position={[0, .56, frontZ + .02]} size={.34} /></>}</group>; }
function MidModel({ blueprint, materials, activity, haze }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <group><mesh geometry={unitBox} scale={[width, height, depth]} material={materials.cabinet} /><HornFlare geometry={midHorn} glowGeometry={midHornGlow} y={.21} frontZ={frontZ} mouthWidth={.56} mouthHeight={.2} throatWidth={.12} throatHeight={.07} depth={.19} materials={materials} /><WooferAssembly size={.19} y={-.1} frontZ={frontZ} materials={materials} /><ReflexPort x={0} y={-.33} frontZ={frontZ + .02} width={.3} height={.042} />{haze && <><LocalGlow color={MID} activity={activity} position={[0, -.1, frontZ + .024]} size={.29} /><LocalGlow color={MID} activity={activity} position={[0, .21, frontZ + .02]} size={.26} /></>}</group>; }
function HighModel({ blueprint, materials, activity, haze }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><HornFlare geometry={highHorn} glowGeometry={highHornGlow} y={0} frontZ={frontZ} mouthWidth={.88} mouthHeight={.38} throatWidth={.12} throatHeight={.08} depth={.36} materials={materials} /><CornerFasteners width={width * .87} height={height * .75} frontZ={frontZ + .022} inset={.06} />{haze && <LocalGlow color={HIGH} activity={activity} position={[0, 0, frontZ + .02]} size={.46} />}</>; }

export function SpeakerMiniature({ kind, activity, selected = false, showHaze = true, idleVisible = false }: Props) { const blueprint = blueprints[kind]; const materials = useSpeakerMaterials(kind, activity); const boxSelection = kind === "full" || kind === "mid"; return <group>{idleVisible && <lineSegments geometry={blueprint.edges} material={idleEdgeMaterial} rotation={kind === "full" ? [-.04, 0, 0] : undefined} />}{kind === "sub" && <SubModel blueprint={blueprint} materials={materials} activity={activity} haze={showHaze} />}{kind === "woofer" && <WooferModel blueprint={blueprint} materials={materials} activity={activity} haze={showHaze} />}{kind === "full" && <FullModel blueprint={blueprint} materials={materials} activity={activity} haze={showHaze} />}{kind === "mid" && <MidModel blueprint={blueprint} materials={materials} activity={activity} haze={showHaze} />}{kind === "high" && <HighModel blueprint={blueprint} materials={materials} activity={activity} haze={showHaze} />}{selected && <mesh geometry={boxSelection ? unitBox : blueprint.cabinet} scale={boxSelection ? [blueprint.body[0] * 1.018, blueprint.body[1] * 1.018, blueprint.body[2] * 1.018] : [1.018, 1.018, 1.018]} rotation={kind === "full" ? [-.04, 0, 0] : undefined} material={selectionMaterial} />}</group>; }
export const speakerBlueprints = blueprints;
