/* Club Craft visual rule: physical PA miniatures stay neutral and matte; activity color belongs only to SpeakerEmitterGlow. */
import * as THREE from "three";
import { Suspense, useEffect, useMemo } from "react";
import type { SpeakerKind } from "@/hooks/useClubAudio";
import { speakerBodyTuple } from "@/lib/speakerDimensions";
import { getSpeakerModel, resolveModelId, type SpeakerModelId } from "@/lib/speakerModels";
import ReggaeSpeakerModel from "@/components/speakers/ReggaeSpeakerModel";
import SceneSpeakerModel from "@/components/speakers/SceneSpeakerModel";
import GlbSpeakerModel from "@/components/speakers/GlbSpeakerModel";
import SpeakerEmitterGlow from "@/components/speakers/SpeakerEmitterGlow";
import type { SpeakerBandActivity } from "@/lib/bandActivity";
import { normalizeCabinetColor } from "@/lib/speakerCabinetColor";

type Props = { kind: SpeakerKind; modelId?: SpeakerModelId; activity: number; bandActivity?: SpeakerBandActivity; selected?: boolean; showHaze?: boolean; idleVisible?: boolean; glowStrength?: number; cabinetColor?: string };
type Blueprint = { body: [number, number, number]; cabinet: THREE.BufferGeometry; edges: THREE.EdgesGeometry };
type SpeakerMaterials = { cabinet: THREE.MeshStandardMaterial; baffle: THREE.MeshStandardMaterial; hornShell: THREE.MeshStandardMaterial; hornEmitter: THREE.MeshStandardMaterial; wooferCone: THREE.MeshStandardMaterial; wooferEmitter: THREE.MeshStandardMaterial };
type HornProps = { geometry: THREE.BufferGeometry; glowGeometry?: THREE.BufferGeometry; x?: number; y: number; frontZ: number; mouthWidth: number; mouthHeight: number; throatWidth: number; throatHeight: number; depth: number; materials: SpeakerMaterials };

const passiveFrameMaterial = new THREE.MeshStandardMaterial({ color: "#72777c", roughness: .74, metalness: .1 });
const passiveDetailMaterial = new THREE.MeshStandardMaterial({ color: "#252a2e", roughness: .88, metalness: .03 });
const hornVoidMaterial = new THREE.MeshBasicMaterial({ color: "#101316", toneMapped: false });
const hornWallMaterials = ["#3b4146", "#4b5157", "#5c6369", "#30363b"].map((color) => new THREE.MeshStandardMaterial({ color, roughness: .9, metalness: .02, side: THREE.DoubleSide }));
const passiveMetalMaterial = new THREE.MeshStandardMaterial({ color: "#a2a8ad", roughness: .5, metalness: .24 });
const passiveFootMaterial = new THREE.MeshStandardMaterial({ color: "#42484d", roughness: .86 });
const selectionMaterial = new THREE.MeshBasicMaterial({ color: "#d5c2a8", transparent: true, opacity: .028, side: THREE.BackSide });
const idleEdgeMaterial = new THREE.LineBasicMaterial({ color: "#666761", transparent: true, opacity: .3 });
const unitBox = new THREE.BoxGeometry(1, 1, 1);
const wooferMount = new THREE.CylinderGeometry(1, 1, .028, 24);
wooferMount.rotateX(Math.PI / 2);
const wooferSurround = new THREE.TorusGeometry(1, .11, 6, 24);
const dustCap = new THREE.SphereGeometry(1, 16, 10);
const fastenerHead = new THREE.CylinderGeometry(.027, .027, .014, 12);
const compressionDriver = new THREE.CylinderGeometry(1, .86, .34, 16);
compressionDriver.rotateX(Math.PI / 2);

function makeChamferCabinet(width: number, height: number, depth: number, taper = 0) { const top = width * (1 - taper); const shape = new THREE.Shape(); shape.moveTo(-width / 2, -height / 2); shape.lineTo(width / 2, -height / 2); shape.lineTo(top / 2, height / 2); shape.lineTo(-top / 2, height / 2); shape.closePath(); const geometry = new THREE.ExtrudeGeometry(shape, { depth, bevelEnabled: true, bevelThickness: .03, bevelSize: .024, bevelSegments: 1, curveSegments: 1 }); geometry.translate(0, 0, -depth / 2); geometry.computeVertexNormals(); return geometry; }
function makeHornFlare(mouthWidth: number, mouthHeight: number, throatWidth: number, throatHeight: number, depth: number) { const vertices = new Float32Array([-mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, -mouthHeight / 2, 0, mouthWidth / 2, mouthHeight / 2, 0, -mouthWidth / 2, mouthHeight / 2, 0, -throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, -throatHeight / 2, -depth, throatWidth / 2, throatHeight / 2, -depth, -throatWidth / 2, throatHeight / 2, -depth]); const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.BufferAttribute(vertices, 3)); geometry.setIndex([0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7]); for (let index = 0; index < 4; index += 1) geometry.addGroup(index * 6, 6, index); geometry.computeVertexNormals(); return geometry; }
function makeConcaveDisc(radius = 1, segments = 32, depth = .16) { const geometry = new THREE.CircleGeometry(radius, segments); const positions = geometry.attributes.position; for (let i = 0; i < positions.count; i += 1) { const x = positions.getX(i); const y = positions.getY(i); const r = Math.min(1, Math.sqrt(x * x + y * y) / radius); positions.setZ(i, -depth * Math.pow(1 - r, 1.6)); } positions.needsUpdate = true; geometry.computeVertexNormals(); return geometry; }

const foldedSubHorn = makeHornFlare(.9, .62, .2, .12, .42); const foldedSubHornGlow = makeHornFlare(.62, .4, .11, .065, .33);
const lowerWooferHorn = makeHornFlare(.9, .63, .2, .12, .42); const lowerWooferHornGlow = makeHornFlare(.62, .4, .11, .07, .32);
const fullHorn = makeHornFlare(.78, .38, .14, .075, .34); const fullHornGlow = makeHornFlare(.52, .22, .08, .042, .26);
const midHorn = makeHornFlare(.68, .43, .1, .065, .28); const midHornGlow = makeHornFlare(.44, .26, .055, .034, .21);
const highHorn = makeHornFlare(.92, .42, .11, .065, .4); const highHornGlow = makeHornFlare(.62, .25, .06, .035, .3);
const concaveWooferCone = makeConcaveDisc(1, 32, .18); const concaveWooferGlow = makeConcaveDisc(1, 32, .145);
function makeBlueprint(body: [number, number, number], taper: number): Blueprint { const cabinet = makeChamferCabinet(...body, taper); return { body, cabinet, edges: new THREE.EdgesGeometry(cabinet, 14) }; }
const blueprints: Record<SpeakerKind, Blueprint> = { sub: makeBlueprint(speakerBodyTuple("sub"), .015), woofer: makeBlueprint(speakerBodyTuple("woofer"), .04), full: makeBlueprint(speakerBodyTuple("full"), .1), mid: makeBlueprint(speakerBodyTuple("mid"), .035), high: makeBlueprint(speakerBodyTuple("high"), .08) };

const neutralCabinetColor = new THREE.Color("#70767b"); const neutralBaffleColor = new THREE.Color("#41474c"); const neutralHornColor = new THREE.Color("#5b6268"); const neutralConeColor = new THREE.Color("#353b40");
function createEmitterMaterial() { return new THREE.MeshStandardMaterial({ color: "#111315", roughness: .72, metalness: 0, emissive: "#000000", emissiveIntensity: 0, side: THREE.DoubleSide, toneMapped: false }); }
function createSpeakerMaterials(cabinetColor: string): SpeakerMaterials { return { cabinet: new THREE.MeshStandardMaterial({ color: cabinetColor, roughness: .84, metalness: .02, emissive: "#000000" }), baffle: new THREE.MeshStandardMaterial({ color: neutralBaffleColor, roughness: .9, metalness: .01, emissive: "#000000" }), hornShell: new THREE.MeshStandardMaterial({ color: neutralHornColor, roughness: .79, metalness: .01, side: THREE.DoubleSide, emissive: "#000000" }), hornEmitter: createEmitterMaterial(), wooferCone: new THREE.MeshStandardMaterial({ color: neutralConeColor, roughness: .8, metalness: .01, side: THREE.DoubleSide, emissive: "#000000" }), wooferEmitter: createEmitterMaterial() }; }
function useSpeakerMaterials(cabinetColor?: string) { const resolved = normalizeCabinetColor(cabinetColor); const materials = useMemo(() => createSpeakerMaterials(resolved), [resolved]); useEffect(() => () => { Object.values(materials).forEach((material) => material.dispose()); }, [materials]); return materials; }

function CabinetFeet({ width, height, depth, count = 2 }: { width: number; height: number; depth: number; count?: number }) { const positions = count === 4 ? [[-.37, -.3], [.37, -.3], [-.37, .3], [.37, .3]] : [[-.34, .12], [.34, .12]]; return <group position={[0, -height / 2 - .05, 0]}>{positions.map(([x, z], index) => <mesh key={index} geometry={unitBox} position={[x * width, 0, z * depth]} scale={[.1, .1, .12]} material={passiveFootMaterial} />)}</group>; }
function CornerFasteners({ width, height, frontZ, inset = .08 }: { width: number; height: number; frontZ: number; inset?: number }) { return <>{[[-1, -1], [1, -1], [-1, 1], [1, 1]].map(([x, y], index) => <mesh key={index} geometry={fastenerHead} rotation={[Math.PI / 2, 0, 0]} position={[x * (width / 2 - inset), y * (height / 2 - inset), frontZ]} material={passiveMetalMaterial} />)}</>; }
function HornLip({ width, height }: { width: number; height: number }) { const thickness = .022; return <><mesh geometry={unitBox} position={[0, height / 2, .012]} scale={[width, thickness, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[0, -height / 2, .012]} scale={[width, thickness, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[-width / 2, 0, .012]} scale={[thickness, height, .028]} material={passiveFrameMaterial} /><mesh geometry={unitBox} position={[width / 2, 0, .012]} scale={[thickness, height, .028]} material={passiveFrameMaterial} /></>; }
function HornFlare({ geometry, glowGeometry, x = 0, y, frontZ, mouthWidth, mouthHeight, throatWidth, throatHeight, depth, materials }: HornProps) { void glowGeometry; const visualDepth = THREE.MathUtils.clamp(depth * .12, .035, .065); const innerWidth = THREE.MathUtils.lerp(throatWidth, mouthWidth, .42); const innerHeight = THREE.MathUtils.lerp(throatHeight, mouthHeight, .42); return <group position={[x, y, frontZ]}><mesh geometry={unitBox} position={[0, 0, -.004]} scale={[mouthWidth * .91, mouthHeight * .84, .018]} material={hornVoidMaterial} /><mesh geometry={geometry} position={[0, 0, visualDepth + .006]} scale={[1, 1, visualDepth / depth]} material={hornWallMaterials} /><mesh geometry={unitBox} position={[0, 0, .012]} scale={[throatWidth * 1.08, throatHeight * 1.08, .022]} material={materials.hornEmitter} /><group position={[0, 0, visualDepth * .42]} scale={[.72, .72, .72]}><HornLip width={innerWidth} height={innerHeight} /></group><group position={[0, 0, visualDepth + .015]}><HornLip width={mouthWidth} height={mouthHeight} /></group></group>; }
function WooferAssembly({ size, y, frontZ, materials }: { size: number; y: number; frontZ: number; materials: SpeakerMaterials }) { return <group position={[0, y, frontZ + .015]}><mesh geometry={wooferMount} scale={[size * 1.12, size * 1.12, 1]} material={materials.baffle} /><mesh geometry={wooferSurround} position={[0, 0, .012]} scale={[size, size, 1]} material={materials.baffle} /><mesh geometry={concaveWooferCone} position={[0, 0, .018]} scale={[size * .82, size * .82, 1]} material={materials.wooferCone} /><mesh geometry={concaveWooferGlow} position={[0, 0, .022]} scale={[size * .64, size * .64, 1]} material={materials.wooferEmitter} /><mesh geometry={dustCap} position={[0, 0, .026]} scale={[size * .16, size * .16, size * .05]} material={passiveDetailMaterial} /></group>; }
function ReflexPort({ x, y, frontZ, width, height }: { x: number; y: number; frontZ: number; width: number; height: number }) { return <mesh geometry={unitBox} position={[x, y, frontZ + .032]} scale={[width, height, .038]} material={passiveDetailMaterial} />; }
function FoldedHorn({ geometry, glowGeometry, x = 0, y, frontZ, mouthWidth, mouthHeight, throatWidth, throatHeight, depth, materials }: HornProps) { return <group><HornFlare geometry={geometry} glowGeometry={glowGeometry} x={x} y={y} frontZ={frontZ} mouthWidth={mouthWidth} mouthHeight={mouthHeight} throatWidth={throatWidth} throatHeight={throatHeight} depth={depth} materials={materials} /><mesh geometry={unitBox} position={[x, y, frontZ - depth - .035]} scale={[throatWidth * .55, throatHeight * .55, .028]} material={materials.hornEmitter} /></group>; }
function RecessedPanel({ width, height, y, frontZ }: { width: number; height: number; y: number; frontZ: number }) { return <group position={[0, y, frontZ]}><mesh geometry={unitBox} scale={[width, height, .045]} material={passiveDetailMaterial} /><group position={[0, 0, .026]}><HornLip width={width} height={height} /></group></group>; }
function HornBraces({ width, height, y, frontZ, vertical = 1 }: { width: number; height: number; y: number; frontZ: number; vertical?: number }) { return <group>{Array.from({ length: vertical }, (_, index) => { const x = (index - (vertical - 1) / 2) * width / (vertical + 1); return <mesh key={index} geometry={unitBox} position={[x, y, frontZ + .018]} scale={[.028, height, .032]} material={passiveFrameMaterial} />; })}<mesh geometry={unitBox} position={[0, y, frontZ + .018]} scale={[width, .025, .032]} material={passiveFrameMaterial} /></group>; }

function SubModel({ blueprint, materials, activity, haze, glowStrength }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean; glowStrength: number }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><RecessedPanel width={width * .91} height={height * .76} y={0} frontZ={frontZ + .006} /><FoldedHorn geometry={foldedSubHorn} glowGeometry={foldedSubHornGlow} x={-.55} y={0} frontZ={frontZ + .04} mouthWidth={.9} mouthHeight={.62} throatWidth={.2} throatHeight={.12} depth={.42} materials={materials} /><FoldedHorn geometry={foldedSubHorn} glowGeometry={foldedSubHornGlow} x={.55} y={0} frontZ={frontZ + .04} mouthWidth={.9} mouthHeight={.62} throatWidth={.2} throatHeight={.12} depth={.42} materials={materials} /><HornBraces width={width * .78} height={height * .62} y={0} frontZ={frontZ + .048} vertical={1} /><CornerFasteners width={width * .9} height={height * .8} frontZ={frontZ + .064} inset={.06} /><CabinetFeet width={width} height={height} depth={depth} count={4} />{haze && <SpeakerEmitterGlow band="low" activity={activity} position={[0, 0, frontZ + .10]} size={.9} strength={glowStrength} />}</>; }
function WooferModel({ blueprint, materials, activity, haze, glowStrength }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean; glowStrength: number }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><RecessedPanel width={width * .84} height={.4} y={.46} frontZ={frontZ} /><WooferAssembly size={.2} y={.46} frontZ={frontZ + .018} materials={materials} /><FoldedHorn geometry={lowerWooferHorn} glowGeometry={lowerWooferHornGlow} y={-.3} frontZ={frontZ + .018} mouthWidth={.9} mouthHeight={.63} throatWidth={.2} throatHeight={.12} depth={.42} materials={materials} /><HornBraces width={.82} height={.55} y={-.3} frontZ={frontZ + .024} vertical={2} /><CornerFasteners width={width * .87} height={height * .87} frontZ={frontZ + .04} /><CabinetFeet width={width} height={height} depth={depth} />{haze && <SpeakerEmitterGlow band="low" activity={activity} position={[0, -.3, frontZ + .085]} size={.58} strength={glowStrength} />}</>; }
function FullModel({ blueprint, materials, lowActivity, highActivity, haze, glowStrength }: { blueprint: Blueprint; materials: SpeakerMaterials; lowActivity: number; highActivity: number; haze: boolean; glowStrength: number }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <group rotation={[-.035, 0, 0]}><mesh geometry={unitBox} scale={[width, height, depth]} material={materials.cabinet} /><RecessedPanel width={width * .88} height={height * .86} y={0} frontZ={frontZ + .006} /><HornFlare geometry={fullHorn} glowGeometry={fullHornGlow} y={.57} frontZ={frontZ + .04} mouthWidth={.78} mouthHeight={.38} throatWidth={.14} throatHeight={.075} depth={.34} materials={materials} /><WooferAssembly size={.32} y={-.16} frontZ={frontZ + .04} materials={materials} /><ReflexPort x={0} y={-.76} frontZ={frontZ + .04} width={.5} height={.06} /><CornerFasteners width={width * .84} height={height * .86} frontZ={frontZ + .067} /><CabinetFeet width={width} height={height} depth={depth} />{haze && <><SpeakerEmitterGlow band="low" activity={lowActivity} position={[0, -.16, frontZ + .105]} size={.38} strength={glowStrength} /><SpeakerEmitterGlow band="high" activity={highActivity} position={[0, .57, frontZ + .11]} size={.32} strength={glowStrength} /></>}</group>; }
function MidModel({ blueprint, materials, activity, haze, glowStrength }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean; glowStrength: number }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <group><mesh geometry={unitBox} scale={[width, height, depth]} material={materials.cabinet} /><RecessedPanel width={width * .88} height={height * .74} y={.02} frontZ={frontZ + .006} /><HornFlare geometry={midHorn} glowGeometry={midHornGlow} y={.04} frontZ={frontZ + .04} mouthWidth={.68} mouthHeight={.43} throatWidth={.1} throatHeight={.065} depth={.28} materials={materials} /><mesh geometry={compressionDriver} position={[0, .04, frontZ - .31]} scale={[.14, .14, .34]} material={passiveMetalMaterial} /><ReflexPort x={0} y={-.32} frontZ={frontZ + .04} width={.36} height={.045} />{haze && <SpeakerEmitterGlow band="mid" activity={activity} position={[0, .04, frontZ + .10]} size={.31} strength={glowStrength} />}</group>; }
function HighModel({ blueprint, materials, activity, haze, glowStrength }: { blueprint: Blueprint; materials: SpeakerMaterials; activity: number; haze: boolean; glowStrength: number }) { const [width, height, depth] = blueprint.body; const frontZ = depth / 2 + .012; return <><mesh geometry={blueprint.cabinet} material={materials.cabinet} /><RecessedPanel width={width * .91} height={height * .73} y={0} frontZ={frontZ + .006} /><HornFlare geometry={highHorn} glowGeometry={highHornGlow} y={0} frontZ={frontZ + .042} mouthWidth={.92} mouthHeight={.42} throatWidth={.11} throatHeight={.065} depth={.4} materials={materials} /><mesh geometry={compressionDriver} position={[0, 0, frontZ - .43]} scale={[.17, .17, .42]} material={passiveMetalMaterial} /><CornerFasteners width={width * .88} height={height * .78} frontZ={frontZ + .067} inset={.06} />{haze && <SpeakerEmitterGlow band="high" activity={activity} position={[0, 0, frontZ + .12]} size={.44} strength={glowStrength} />}</>; }

function ModernSpeakerMiniature({ kind, activity, bandActivity, selected = false, showHaze = true, idleVisible = false, glowStrength = .8, cabinetColor }: Props) { const blueprint = blueprints[kind]; const materials = useSpeakerMaterials(cabinetColor); const boxSelection = kind === "full" || kind === "mid"; const bands = bandActivity ?? { overall: activity, low: activity, mid: activity, high: activity }; return <group>{idleVisible && <lineSegments geometry={blueprint.edges} material={idleEdgeMaterial} rotation={kind === "full" ? [-.04, 0, 0] : undefined} />}{kind === "sub" && <SubModel blueprint={blueprint} materials={materials} activity={bands.low} haze={showHaze} glowStrength={glowStrength} />}{kind === "woofer" && <WooferModel blueprint={blueprint} materials={materials} activity={bands.low} haze={showHaze} glowStrength={glowStrength} />}{kind === "full" && <FullModel blueprint={blueprint} materials={materials} lowActivity={bands.low} highActivity={bands.high} haze={showHaze} glowStrength={glowStrength} />}{kind === "mid" && <MidModel blueprint={blueprint} materials={materials} activity={bands.mid} haze={showHaze} glowStrength={glowStrength} />}{kind === "high" && <HighModel blueprint={blueprint} materials={materials} activity={bands.high} haze={showHaze} glowStrength={glowStrength} />}{selected && <mesh geometry={boxSelection ? unitBox : blueprint.cabinet} scale={boxSelection ? [blueprint.body[0] * 1.018, blueprint.body[1] * 1.018, blueprint.body[2] * 1.018] : [1.018, 1.018, 1.018]} rotation={kind === "full" ? [-.04, 0, 0] : undefined} material={selectionMaterial} />}</group>; }
function ProceduralSpeaker({ modelId, kind, activity, bandActivity, selected, showHaze, idleVisible, glowStrength, cabinetColor }: { modelId: SpeakerModelId; kind: SpeakerKind; activity: number; bandActivity?: SpeakerBandActivity; selected: boolean; showHaze: boolean; idleVisible: boolean; glowStrength: number; cabinetColor?: string }) { const model = getSpeakerModel(modelId, kind); if (model.family === "reggae") return <ReggaeSpeakerModel modelId={modelId} kind={kind} activity={activity} bandActivity={bandActivity} selected={selected} glowStrength={glowStrength} cabinetColor={cabinetColor} />; if (model.family === "modern") return <ModernSpeakerMiniature kind={kind} activity={activity} bandActivity={bandActivity} selected={selected} showHaze={showHaze} idleVisible={idleVisible} glowStrength={glowStrength} cabinetColor={cabinetColor} />; return <SceneSpeakerModel modelId={modelId} kind={kind} activity={activity} bandActivity={bandActivity} selected={selected} cabinetColor={cabinetColor} />; }
export function SpeakerMiniature({ kind, modelId, activity, bandActivity, selected = false, showHaze = true, idleVisible = false, glowStrength = .8, cabinetColor }: Props) { const resolvedModelId = resolveModelId(modelId, kind); const model = getSpeakerModel(resolvedModelId, kind); const fallback = <ProceduralSpeaker modelId={resolvedModelId} kind={kind} activity={activity} bandActivity={bandActivity} selected={selected} showHaze={showHaze} idleVisible={idleVisible} glowStrength={glowStrength} cabinetColor={cabinetColor} />; return model.visual.renderer === "glb" ? <Suspense fallback={fallback}><GlbSpeakerModel visual={model.visual} body={model.body} activity={activity} bandActivity={bandActivity} cabinetColor={cabinetColor} /></Suspense> : fallback; }
export const speakerBlueprints = blueprints;
