/* Validation-only route: bright neutral illumination for comparing modern and reggae cabinet geometry, not the production club lighting. */
import { Canvas, useThree } from "@react-three/fiber";
import { useEffect } from "react";
import { SpeakerMiniature, speakerBlueprints } from "@/components/SpeakerMiniature";
import type { SpeakerKind } from "@/hooks/useClubAudio";
import { getSpeakerModel, SPEAKER_MODELS, type SpeakerModelId } from "@/lib/speakerModels";
import "../speaker-model-validation.css";

type Angle = "front" | "three-quarter" | "three-quarter-left" | "three-quarter-right" | "side";
type ShownSpeaker = { kind: SpeakerKind; modelId?: SpeakerModelId };
const kinds: SpeakerKind[] = ["sub", "woofer", "full", "mid", "high"];
const labels: Record<SpeakerKind, string> = { sub: "SUB", woofer: "WOOFER", full: "FULL RANGE", mid: "MID", high: "HIGH" };
function bodyFor(item: ShownSpeaker) { return item.modelId ? getSpeakerModel(item.modelId, item.kind).body : { width: speakerBlueprints[item.kind].body[0], height: speakerBlueprints[item.kind].body[1], depth: speakerBlueprints[item.kind].body[2] }; }
function CameraPose({ angle, item }: { angle?: Angle; item?: ShownSpeaker }) { const { camera } = useThree(); useEffect(() => { const body = item ? bodyFor(item) : undefined; const height = body?.height ?? .85; const focusY = height / 2; const distance = Math.max(3.15, height * 2.65); const quarterY = focusY + Math.max(.72, height * .52); const positions: Record<Angle, [number, number, number]> = { front: [0, focusY + .15, distance], "three-quarter": [distance * .68, quarterY, distance * .78], "three-quarter-left": [-distance * .68, quarterY, distance * .78], "three-quarter-right": [distance * .68, quarterY, distance * .78], side: [distance, focusY + .32, 0] }; const position: [number, number, number] = angle ? positions[angle] : [7.1, 4.5, 8.6]; camera.position.set(...position); camera.lookAt(0, focusY, 0); }, [angle, camera, item]); return null; }
function NeutralExposure({ dark }: { dark: boolean }) { const { gl } = useThree(); useEffect(() => { const previous = gl.toneMappingExposure; gl.toneMappingExposure = dark ? .88 : 1.05; return () => { gl.toneMappingExposure = previous; }; }, [dark, gl]); return null; }
function NeutralScene({ shown, active, dark }: { shown: ShownSpeaker[]; active: boolean; dark: boolean }) { const xFor = (index: number) => shown.length === 1 ? 0 : (index - 2) * 2.1; return <><color attach="background" args={[dark ? "#050606" : "#4a4943"]} /><ambientLight intensity={dark ? .16 : .78} /><hemisphereLight args={[dark ? "#252721" : "#fff8e7", dark ? "#020302" : "#363733", dark ? .34 : .65]} /><directionalLight position={[1.5, 4.2, 7]} intensity={dark ? .28 : 1.6} color="#fff2d6" />{!dark && <><directionalLight position={[-5, 4, 3]} intensity={.55} color="#d8e0e0" /><directionalLight position={[0, 5, -4]} intensity={.25} color="#f4dfbd" /></>}<mesh rotation={[-Math.PI / 2, 0, 0]}><planeGeometry args={[15, 12]} /><meshStandardMaterial color={dark ? "#0a0b0a" : "#777469"} roughness={.92} /></mesh>{shown.map((item, index) => { const body = bodyFor(item); return <group key={item.modelId ?? item.kind} position={[xFor(index), body.height / 2, 0]}><SpeakerMiniature kind={item.kind} modelId={item.modelId} activity={active ? .78 : 0} showHaze={false} /></group>; })}</>; }
export default function SpeakerModelValidation() { const params = new URLSearchParams(window.location.search); const angle = params.get("angle") as Angle | null; const validAngle = angle === "front" || angle === "three-quarter" || angle === "three-quarter-left" || angle === "three-quarter-right" || angle === "side" ? angle : undefined; const requestedModelId = params.get("modelId") as SpeakerModelId | null; const validModelId = requestedModelId && SPEAKER_MODELS[requestedModelId] ? requestedModelId : undefined; const requestedKind = params.get("kind") as SpeakerKind | null; const validKind = requestedKind && kinds.includes(requestedKind) ? requestedKind : undefined; const shown: ShownSpeaker[] = validModelId ? [{ kind: SPEAKER_MODELS[validModelId].kind, modelId: validModelId }] : validKind ? [{ kind: validKind }] : validAngle ? [{ kind: "full" }] : kinds.map((kind) => ({ kind })); const active = params.get("active") === "1"; const dark = params.get("dark") === "1"; const caption = validModelId ? SPEAKER_MODELS[validModelId].label : labels[shown[0].kind]; return <main className="speaker-model-lab"><header><strong>Club Craft</strong><span>{active ? "Band Activity Color Verification" : "PA Speaker Geometry Verification"}</span></header><section className="speaker-model-canvas"><Canvas camera={{ fov: 40 }} dpr={[1, 1.5]}><NeutralExposure dark={dark} /><CameraPose angle={validAngle} item={shown.length === 1 ? shown[0] : undefined} /><NeutralScene shown={shown} active={active} dark={dark} /></Canvas></section>{shown.length === 1 ? <p className="speaker-model-caption">{caption} — {validAngle?.startsWith("three-quarter") ? "3/4" : validAngle ?? "front"}</p> : <div className="speaker-model-labels">{kinds.map((kind) => <span key={kind}>{labels[kind]}</span>)}</div>}</main>; }
